# -*- coding: utf-8 -*-
"""
scrape_pieceful.py

Pieceful Coffee Roaster(pieceful.thebase.in、愛媛県松山市萱町1丁目4-1
第一グリーンビル101、自家焙煎豆のオンライン販売)の商品情報を取得する。
BASE。

【住所について】
実データ確認済み(2026-09時点): 公式ストアの特定商取引法ページ
(https://pieceful.thebase.in/law)で「〒790-0813 愛媛県松山市萱町1丁目
4-1 第一グリーンビル101」と一致確認済み。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【非コーヒー豆商品の除外について】
実データ確認済み(サンプル調査): パッケージラベルなしコーヒーバッグ各種
(Dip Style coffee、ドリップバッグ形態)・店主のおすすめコーヒー豆SET
(複数銘柄アソート、110g×3種/180g×3種)が非対象。NON_BEAN_KEYWORDSで除外
する。

【重量違いの重複について】
実データ確認済み: 「コロンビア　ラ・ラハ　スーダンルメ ウォッシュド」の
ように100g/200gの2サイズで個別商品登録されている銘柄がある。商品名末尾の
重量を除いた基準名でグルーピングし、最小重量(100g)を代表として採用する。

【flavor_notes/farm_note(テイスティングノート・農園情報)について
(2026-09-20追記)】
実データ確認済み(全43商品サンプル調査): 他のBASE系店舗と共通のテーマの
p[class*="item-detail_description"]要素に「【カッピングプロファイル】」
見出し直後の1行(風味タグをカンマ区切りで列挙)と、「国：」「標高：」
「エリア：」/「生産エリア：」「農園：」/「農園名：」「生産者：」/
「農園主：」「品種：」「生産処理：」ラベルの農園情報が続く一貫した構造
だったが、この要素自体を一切読んでいなかった。カッピングプロファイル
直後の1行をflavor_notesとして採用し、ラベル値はfarm_note用フィールドに
反映する。末尾の「※豆の状態での販売となります」以降(farm補足の長文説明
含む)は対象としない。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status, normalize_processing_method

SHOP_INFO = {
    "name": "Pieceful Coffee Roaster",
    "url": "https://pieceful.thebase.in/",
    "platform": "BASE",
    "address": "愛媛県松山市萱町1丁目4-1 第一グリーンビル101",
    "prefecture": "愛媛県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://pieceful.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "コーヒーバッグ", "Dip Style", "SET", "セット",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
CUPPING_HEADING = "【カッピングプロファイル】"
FARM_LABEL_PATTERN = re.compile(r"^(国|標高|エリア|生産エリア|農園名|農園|生産者|農園主|品種|生産処理|焙煎度)[：:]\s*(.*)$")
FARM_LABEL_TO_FIELD = {
    "標高": "altitude_note",
    "エリア": "region_detail",
    "生産エリア": "region_detail",
    "農園名": "farm_name",
    "農園": "farm_name",
    "生産者": "producer_name",
    "農園主": "producer_name",
    "品種": "variety_note",
}


def parse_flavor_and_farm(soup: BeautifulSoup) -> tuple[str | None, dict, str | None]:
    """理由はモジュールdocstring参照。"""
    el = soup.select_one('p[class*="item-detail_description"]')
    if not el:
        return None, {}, None
    flavor_notes = None
    farm: dict = {}
    processing_raw = None
    next_is_flavor = False
    for raw_line in el.get_text(separator="\n").split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        if line.startswith("※"):
            break
        if line == CUPPING_HEADING:
            next_is_flavor = True
            continue
        if next_is_flavor:
            flavor_notes = line
            next_is_flavor = False
            continue
        m = FARM_LABEL_PATTERN.match(line)
        if m:
            label, value = m.group(1), m.group(2).strip()
            if label in FARM_LABEL_TO_FIELD and value:
                farm[FARM_LABEL_TO_FIELD[label]] = value
            elif label == "生産処理" and value:
                processing_raw = value
    return flavor_notes, farm, processing_raw


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"] or normalize_processing_method(item.get("processing_method_raw")),
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "farm_name": item.get("farm", {}).get("farm_name"),
        "producer_name": item.get("farm", {}).get("producer_name"),
        "region_detail": item.get("farm", {}).get("region_detail"),
        "altitude_note": item.get("farm", {}).get("altitude_note"),
        "variety_note": item.get("farm", {}).get("variety_note"),
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            soup = fetch_page(product_url)
            fields = extract_og_fields(soup)
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        flavor_notes, farm, processing_raw = parse_flavor_and_farm(soup)
        all_items.append({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "flavor_notes": flavor_notes,
            "farm": farm,
            "processing_method_raw": processing_raw,
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_pieceful.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_pieceful.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
