# -*- coding: utf-8 -*-
"""
scrape_akekure.py

明暮焙煎所 / AKEKURE BEANS(akekurebeans.thebase.in、〒654-0033 兵庫県神戸市
須磨区東町1-2-9、自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量違いの重複について】
実データ確認済み: 全80件中、定番ブレンド4種+シングルオリジン11種の
計15銘柄が100g/200g/500gの3サイズで個別商品登録されている。商品名末尾
の重量を除いた基準名でグルーピングし、最小重量(100g)を代表として採用
する。

【非コーヒー豆商品の除外について】
実データ確認済み: アイスコーヒーリキッド(単本/セット/SUMMER GIFT各種
組み合わせ)・クラッシュドコーヒーゼリー(単本/セット/SUMMER GIFT組み
合わせ)・カフェオレベース(無糖/加糖/デカフェ、単品/2本セット/GIFT組み
合わせ)・コーヒー豆定期購買コース(複数銘柄の詰め合わせ定期便で単一
銘柄ではない)・詰め合わせギフト(３種のブレンド詰め合わせ、3種の
コーヒーバッグ詰め合わせギフト)・あずま袋(雑貨)・HARIOコーヒー
メジャースプーン(器具)・カスカラシロップ・コーヒーバッグアソート
(20袋/50袋パック、ドリップバッグ形態で単一銘柄の焙煎豆ではない)が
非対象。NON_BEAN_KEYWORDSで除外する。残り15銘柄(重複排除後)を対象と
する。

【flavor_notes(2026-09-21追記)】
実データ確認済み: og:descriptionにテイスティング文が入っているが、
商品タイプ毎に構造が異なる(対象15件全てで確認)。(1)季節限定ブレンドは
「|| ORIGIN ||国名|| TASTE ||記述語」という構造化欄を持つ、(2)単一
農園ロットは「地域：/農園主：/標高：/品種：/精製：/焙煎：<焙煎度>」の
スペック欄の直後に「|| TASTE ||記述語」または記述語がそのまま続き、
産地の背景ストーリーが地続きで続く、(3)定番オリジナルブレンドは
スペック欄が無くテイスティング文のみ。いずれも末尾に「深み/甘み/酸味」
のダイヤモンド5段階評価と「【送料】」以降の配送案内が続く。ORIGIN欄・
スペック欄・TASTE欄ラベル・評価行・「【送料】」以降を除去した残りを
採用する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "明暮焙煎所 / AKEKURE BEANS",
    "url": "https://akekurebeans.thebase.in/",
    "platform": "BASE",
    "address": "兵庫県神戸市須磨区東町1-2-9",
    "prefecture": "兵庫県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://akekurebeans.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "アイスコーヒーリキッド", "コーヒーゼリー", "カフェオレベース",
    "定期購買", "詰め合わせ", "あずま袋", "メジャースプーン",
    "カスカラシロップ", "コーヒーバッグ",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")

FLAVOR_SHIP_STOP_PATTERN = re.compile(r"【送料】")
FLAVOR_UNDERSCORE_RUN_PATTERN = re.compile(r"_{3,}")
FLAVOR_ORIGIN_BLOCK_PATTERN = re.compile(r"\|\|\s*ORIGIN\s*\|\|.*?(?=\|\|\s*TASTE\s*\|\||\Z)", re.DOTALL)
FLAVOR_TASTE_LABEL_PATTERN = re.compile(r"\|\|\s*TASTE\s*\|\|\s*")
FLAVOR_RATING_LINE_PATTERN = re.compile(r"(深み|甘み|酸味|コク|苦味)[　\s]*[◆◇]{3,6}")
FLAVOR_SPEC_BLOCK_CUT_PATTERN = re.compile(r".*焙煎[：:]\s*(?:中深煎|中煎|深煎|浅煎)", re.DOTALL)


def extract_flavor_notes(description: str | None) -> str | None:
    """理由はモジュールdocstring参照。"""
    if not description:
        return None
    stop_m = FLAVOR_SHIP_STOP_PATTERN.search(description)
    text = description[: stop_m.start()] if stop_m else description

    text = FLAVOR_ORIGIN_BLOCK_PATTERN.sub("", text)
    text = FLAVOR_SPEC_BLOCK_CUT_PATTERN.sub("", text, count=1)
    text = FLAVOR_TASTE_LABEL_PATTERN.sub("", text)
    text = FLAVOR_RATING_LINE_PATTERN.sub("", text)
    text = FLAVOR_UNDERSCORE_RUN_PATTERN.sub(" ", text)
    text = text.strip()
    return text or None


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    description = desc_el["content"] if desc_el and desc_el.get("content") else None
    return {"title": title, "price": price, "flavor_notes": extract_flavor_notes(description)}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({
            "title": fields["title"], "price": fields["price"], "url": product_url,
            "flavor_notes": fields.get("flavor_notes"),
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_akekure.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_akekure.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
