# -*- coding: utf-8 -*-
"""
scrape_coffeenote.py

coffee beans & tools note(coffeenote.shopselect.net、愛知県名古屋市
千種区東山通1-30-9、覚王山エリアの自家焙煎豆のオンライン販売)の商品
情報を取得する。

【プラットフォームについて】
候補リストではShopSelect(GMOの新しいECサービス)という未調査の
プラットフォームとして挙げられていたが、実データ確認の結果、robots.txt
が他のBASEショップと全く同一の記述("Generated by GRP")であり、URL構造
(/items/N)・sitemap.xml形式・商品ページのog:titleサフィックスに至るまで
BASEと完全に一致することを確認した(og:titleの末尾が実際に
"... powered by BASE"となっている)。つまりshopselect.netドメインは
BASEの別ブランド/カスタムドメインであり、実装上はBASEショップとして
scrape_trunkcoffee.py・scrape_kamecoffee.pyと同じ方式で扱える。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated
by GRP")。curl/python-requests等は個別にDisallow: /指定があるが、
User-agent: *ルールでは実質許可。本スクレイパーは識別可能な独自
User-Agentを使用する。

【商品の大半が非コーヒー豆商品であることについて】
実データ確認済み: sitemap.xmlに含まれる全239商品のうち、実際の焙煎豆
単品は24件のみで、残り215件はHARIO/Kalita/CAFEC/KINTO/Fellow/
LOVERAMICS/Comandante等のドリッパー・グラインダー・電気ケトル・
ペーパーフィルター・カップ&ソーサー等の器具・食器である。TRUNK COFFEE
と同様、キーワードのブラックリスト方式では網羅しきれないため、実データで
確認した「焙煎豆単品の商品名は必ず先頭が重量表記(例: 100g, ・500g )で
始まる」という命名規則を使い、先頭が半角数字+g/ｇで始まるものだけを
焙煎豆候補として採用するホワイトリスト方式を採用する(TRUNK COFFEEの
scrape_trunkcoffee.pyと同じロジック)。この方式は「定期便｜300g　覚王山
ミディアムブレンド」のような定期便(サブスクリプション)商品(先頭が
「定期便｜」で始まり重量から始まらない)も自然に除外できることを確認済み。

【重量バリエーションについて】
実データ確認済み: 6銘柄が100g/200g/500gの3サイズ、1銘柄(覚王山
ミディアムブレンド)は500gのみで登録されている。商品名から重量表記を
除いた基準名でグルーピングし、最小重量を代表として採用する。

【表記ゆれについて】
実データ確認済み: 「メキシコ産デカフェ」銘柄のみ、100g版の商品名が
英語表記主体("100g MEXICO Decafe 【メキシコ｜チアパス｜...】")、200g/
500g版が日本語表記主体("200g デカフェ　メキシコ　チアパス　...　MEXICO
Decafe")と語順が異なり、単純な基準名グルーピングでは別商品として扱われて
しまう。TITLE_ALIASESで100g版のタイトルを200g/500g版と同じ基準名に
正規化してから重複排除する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "coffee beans & tools note",
    "url": "https://coffeenote.shopselect.net/",
    "platform": "BASE(ShopSelectドメイン)",
    "address": "愛知県名古屋市千種区東山通1-30-9",
    "prefecture": "愛知県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://coffeenote.shopselect.net"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
BEAN_START_PATTERN = re.compile(r"^\d+\s*[gｇ]")
KEY_NOISE_PATTERN = re.compile(r"[^\w一-龠ぁ-んァ-ヶー]+")
# 実データ確認済み(docstring参照): メキシコ産デカフェの100g版のみ英語表記
# 主体で語順が異なるため、基準名グルーピング前に正規化する。
TITLE_ALIASES = {
    "MEXICO Decafe 【メキシコ｜チアパス｜マウンテンウォーター製法｜有機JAS認証 】":
        "デカフェ メキシコ チアパス マウンテンウォーター製法 有機JAS認証 MEXICO Decafe",
}


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def normalize_after_weight_strip(title: str) -> str:
    without_weight = WEIGHT_PATTERN.sub("", title, count=1).strip()
    return TITLE_ALIASES.get(without_weight, without_weight)


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()

    if not BEAN_START_PATTERN.match(title):
        return None

    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def build_group_key(title: str) -> str:
    normalized = normalize_after_weight_strip(title)
    return KEY_NOISE_PATTERN.sub("", normalized).lower()


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = build_group_key(item["title"])
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = re.sub(r"\s+", " ", item["title"]).strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_coffeenote.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_coffeenote.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
