# -*- coding: utf-8 -*-
"""
scrape_bahnhof.py

自家焙煎珈琲工房 カフェ バーンホーフ(bahnhof.jp、大阪市福島区吉野1-14-8、
自家焙煎豆のオンライン販売。ショップはbahnhof.official.ec)の商品情報を
取得する。official.ecはBASEプラットフォームのファミリードメイン。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量について】
実データ確認済み: 商品名・商品説明のいずれにも内容量(g)の記載がなく、
購入時に「豆」/「粉」の挽き方バリエーションのみを選択する形式(価格は
共通)。そのためweight_gは全件nullとしている。

【非コーヒー豆商品の除外について】
実データ確認済み: ドリップバッグコーヒー各種(個包装フォーマット)・
アイスコーヒー各種(瓶入り液体、ギフトセット含む)・ギフト(袋/箱の
包材そのもの)・焼き菓子各種(クーヘン・フロランタン・フィナンシェ・
ショコベアー・マンデルショコ・サブレ・シャウム・ブルーメ)・
珈琲器具各種(コーヒーミル・ドリップポット・ステンレスポット・
サーバー・有田焼ドリッパー・ペーパーフィルター・バースプーン・
棒状温度計セット・メジャースプーン)が非対象。NON_BEAN_KEYWORDSで
除外する。
"""

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "バーンホーフ",
    "url": "https://www.bahnhof.jp/",
    "platform": "BASE",
    "address": "大阪府大阪市福島区吉野1-14-8",
    "prefecture": "大阪府",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://bahnhof.official.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ドリップバッグ", "アイスコーヒー", "ギフト", "クーヘン", "フロランタン",
    "フィナンシェ", "ショコベアー", "マンデルショコ", "サブレ", "シャウム",
    "ブルーメ", "コーヒーミル", "ドリップポット", "ステンレス ポット", "サーバー",
    "ドリッパー", "ペーパーフィルター", "バースプーン", "温度計", "メジャースプーン",
]


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": None,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record({"title": fields["title"], "price": fields["price"], "url": product_url})
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_bahnhof.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_bahnhof.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
