# -*- coding: utf-8 -*-
"""
scrape_konasnow.py

自家焙煎珈琲専門店「珈琲豆 山倉」(konasnow.base.shop、新潟県新潟市江南区
西山字屋敷付520番1〈株式会社山倉〉、自家焙煎豆のオンライン販売)の商品
情報を取得する。BASE。

過去の経緯: 埼玉・栃木・群馬・山梨の各バッチで「珈琲豆 山倉」が検索
スニペット経由で誤って各県の店舗として報告される事故が繰り返し発生して
いたが、新潟県バッチの調査で店舗自身の特定商取引法ページから新潟市
江南区が正式な運営者住所であることを確認できたため、ここで実装する。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【お得用(200g)の重複について】
実データ確認済み: 通常サイズ(100g)の主な銘柄について「お得用」「お徳用」
「まとめ買いで50円お得！」と接頭辞/接尾辞が付いた200gバージョンが別
商品として登録されている。これらの接頭辞・接尾辞と重量を除いた基準名で
グルーピングし、最小重量(100g)を代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み: コーヒーリキュール(amarelo)・各種ギフト・大谷翔平
コラボウイスキー(OHTANI WHISKY)・厚岸/イチローズモルト/嘉之助等の
ウイスキー(コーヒー豆店だが酒類も併売)・アイスコーヒー1000mlボトル
(液体、100gの焙煎豆版とは別に除外)・「Base限定商品」の1kg各種粉豆
バンドル(浅中深3種の詰め合わせで単一銘柄と特定できない)が非対象。
NON_BEAN_KEYWORDSで除外する。

【flavor_notes/farm_note(テイスティングノート・農園情報)について
(2026-09-20追記)】
実データ確認済み(サンプル調査): 他のBASE系店舗と共通のテーマの
p[class*="item-detail_description"]要素に「原産国」「農園」「生産地」
「精製方法」「標高」「焙煎」ラベル(コロン・スペース区切りが混在)、
「苦み/コク/酸味/香り/甘み」の★段階評価、店主による風味紹介文が入って
いるが、この要素自体を一切読んでいなかった。風味紹介文の位置が評価の
前後どちらに来るか商品によって異なるため、ラベル行・評価行(★を含む
行)・Instagramクレジット等の定型フッター(「イラスト」「アカウント」を
含む行、「@」を含む行)を除いた残りの自由文を全てflavor_notesとして
採用する。ラベル値は「農園」「生産地」「標高」「精製方法」を
farm_note用フィールドに反映する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status, normalize_processing_method

SHOP_INFO = {
    "name": "珈琲豆 山倉",
    "url": "https://coffee-yamakura.com/",
    "platform": "BASE",
    "address": "新潟県新潟市江南区西山字屋敷付520番1",
    "prefecture": "新潟県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://konasnow.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "コーヒーリキュール", "ギフト", "WHISKY", "蒸留所", "モルト", "1000ml", "限定商品",
]
DISCOUNT_TOKEN_PATTERN = re.compile(r"お得用|お徳用|まとめ買いで\d+円お得！")
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
FARM_LABEL_PATTERN = re.compile(r"^(原産国|農園|生産地|精製方法|標高|焙煎)[：:]?[\s　]*(.*)$")
FARM_LABEL_TO_FIELD = {
    "農園": "farm_name",
    "生産地": "region_detail",
    "標高": "altitude_note",
}
FLAVOR_STOP_KEYWORDS = ("イラスト", "アカウント")


def parse_flavor_and_farm(soup: BeautifulSoup) -> tuple[str | None, dict, str | None]:
    """理由はモジュールdocstring参照。"""
    el = soup.select_one('p[class*="item-detail_description"]')
    if not el:
        return None, {}, None
    farm: dict = {}
    processing_raw = None
    flavor_lines = []
    collecting = True
    for raw_line in el.get_text(separator="\n").split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        if "★" in line or "☆" in line:
            continue
        if any(kw in line for kw in FLAVOR_STOP_KEYWORDS) or "@" in line or line.lower().startswith("http"):
            collecting = False
            continue
        m = FARM_LABEL_PATTERN.match(line)
        if m:
            label, value = m.group(1), m.group(2).strip()
            if label in FARM_LABEL_TO_FIELD and value:
                farm[FARM_LABEL_TO_FIELD[label]] = value
            elif label == "精製方法" and value:
                processing_raw = value
            continue
        if collecting:
            flavor_lines.append(line)
    flavor_notes = "".join(flavor_lines) or None
    return flavor_notes, farm, processing_raw


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = DISCOUNT_TOKEN_PATTERN.sub("", item["title"])
        base_name = WEIGHT_PATTERN.sub("", base_name).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = DISCOUNT_TOKEN_PATTERN.sub("", item["title"]).strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"] or normalize_processing_method(item.get("processing_method_raw")),
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "farm_name": item.get("farm", {}).get("farm_name"),
        "region_detail": item.get("farm", {}).get("region_detail"),
        "altitude_note": item.get("farm", {}).get("altitude_note"),
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            soup = fetch_page(product_url)
            fields = extract_og_fields(soup)
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        flavor_notes, farm, processing_raw = parse_flavor_and_farm(soup)
        all_items.append({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "flavor_notes": flavor_notes,
            "farm": farm,
            "processing_method_raw": processing_raw,
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_konasnow.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_konasnow.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
