# -*- coding: utf-8 -*-
"""
scrape_rootcoffee.py

ROOT COFFEE(rootcoffee.buyshop.jp、東京都大田区池上)の商品情報を取得する。
BUYSHOP(買えるホームページ)という新ドメイン形態だが、robots.txt・
JSON-LD構造ともにBASE標準と完全に同一(「Generated by GRP」ヘッダ、
BASEの旧ブランドとして同一インフラ上で運用されていることを実データ確認済み)。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述(curl/python-requests
等は個別にDisallow: /指定があるが、User-agent: *ルールでは/cart/・/web_cart/・
/shops/・/api/shops/・違反報告ページ以外はAllow: /)。本スクレイパーは
識別可能な独自User-Agentを使用するため該当しない。

【生豆(未焙煎豆)の除外について】
実データ確認済み: 焙煎豆(100g/200g/300g)8銘柄に加えて、同じ銘柄の一部で
「生豆」(未焙煎、100g/200g)というバリエーションも販売されている。この
プロジェクトの対象は焙煎済み豆のためNON_BEAN_KEYWORDSで除外する
(scrape_etop.py・scrape_beescoffee.pyと同じ扱い)。

【重量バリエーションについて】
実データ確認済み: 同一銘柄が100g/200g/300gの3商品(別URL)として個別に
掲載されている(重量選択式ではなく商品自体が別)。全商品を個別商品として
そのまま収録し、weight_gは商品名からWEIGHT_PATTERNで抽出する。

【flavor_notes/farm_note(テイスティングノート・農園情報)について
(2026-09-20追記)】
実データ確認済み: JSON-LD Productのdescriptionフィールドに、店主による
1文の風味紹介文、空行、「生産国 : 」「地域 : 」「生産者 : 」「標高 : 」
「加工 : 」「品種 : 」「収穫年 : 」「焙煎度 : 」ラベル(プレーンテキスト、
HTMLタグ無し)が続く一貫した構造があったが、価格・在庫状況のみ取得し
このフィールド自体を一切読んでいなかった。先頭の空行より前の1行を
flavor_notesとして採用し、「地域」「生産者」「標高」「品種」「加工」
ラベルはfarm_note用フィールドに反映する。
"""

import json
import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status, normalize_processing_method
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "ROOT COFFEE",
    "url": "https://rootcoffee.buyshop.jp/",
    "platform": "BASE",
    "address": "東京都大田区池上",
    "prefecture": "東京都",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://rootcoffee.buyshop.jp"
CRAWL_DELAY_SECONDS = 1.5
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["生豆"]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
FARM_LABEL_PATTERN = re.compile(r"^(生産国|地域|生産者|標高|加工|品種|収穫年|焙煎度)\s*[：:]\s*(.*)$")
FARM_LABEL_TO_FIELD = {
    "地域": "region_detail",
    "生産者": "producer_name",
    "標高": "altitude_note",
    "品種": "variety_note",
}


def parse_flavor_and_farm(description: str) -> tuple[str | None, dict, str | None]:
    """理由はモジュールdocstring参照。"""
    if not description:
        return None, {}, None
    lines = [line.strip() for line in description.split("\n")]
    flavor_notes = lines[0].strip() if lines and lines[0].strip() else None
    farm: dict = {}
    processing_raw = None
    for line in lines[1:]:
        if not line:
            continue
        m = FARM_LABEL_PATTERN.match(line)
        if not m:
            continue
        label, value = m.group(1), m.group(2).strip()
        if label in FARM_LABEL_TO_FIELD and value:
            farm[FARM_LABEL_TO_FIELD[label]] = value
        elif label == "加工" and value:
            processing_raw = value
    return flavor_notes, farm, processing_raw


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_jsonld_product(soup: BeautifulSoup) -> dict | None:
    for script in soup.find_all("script", attrs={"type": "application/ld+json"}):
        text = script.string or script.get_text() or ""
        try:
            data = json.loads(text)
        except json.JSONDecodeError:
            continue
        if isinstance(data, dict) and data.get("@type") == "Product":
            return data
    return None


def build_record(product_url: str, product: dict) -> dict | None:
    title = (product.get("name") or "").strip()
    if not title:
        return None
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None

    parsed = parse_product(title)

    if parsed["is_flavored"]:
        offers = product.get("offers") or {}
        price = int(offers["price"]) if offers.get("price") is not None else None
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": price,
            "product_url": product_url,
        }

    offers = product.get("offers") or {}
    price = int(offers["price"]) if offers.get("price") is not None else None
    availability = offers.get("availability") or ""
    structural_out_of_stock = "InStock" not in availability
    stock_status = detect_stock_status(title, structural_out_of_stock)

    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None
    flavor_notes, farm, processing_raw = parse_flavor_and_farm(product.get("description"))

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"] or normalize_processing_method(processing_raw),
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "farm_name": farm.get("farm_name"),
        "producer_name": farm.get("producer_name"),
        "region_detail": farm.get("region_detail"),
        "altitude_note": farm.get("altitude_note"),
        "variety_note": farm.get("variety_note"),
        "flavor_notes": flavor_notes,
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": price,
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": product_url,
    }


def parse_product_detail(url: str) -> dict | None:
    soup = fetch_page(url)
    product = extract_jsonld_product(soup)
    if not product:
        return None
    return build_record(url, product)


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    urls = []
    for loc in soup.find_all("loc"):
        text = loc.get_text(strip=True)
        if "/items/" in text:
            urls.append(text)
    return urls


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            soup = fetch_page(product_url)
            product = extract_jsonld_product(soup)
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue

        if not product:
            continue
        title = (product.get("name") or "").strip()
        if is_unchanged(prev, raw_name=title):
            records.append(prev)
            continue

        detail = build_record(product_url, product)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)
        import time
        time.sleep(CRAWL_DELAY_SECONDS)

    return records, flavored_records


if __name__ == "__main__":
    import sys

    if len(sys.argv) > 1:
        result = parse_product_detail(sys.argv[1])
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        records, flavored_records = scrape_all_products()
        output = {
            "shop": SHOP_INFO,
            "products": records,
            "flavored_products_excluded": flavored_records,
        }
        with open("data_rootcoffee.json", "w", encoding="utf-8") as f:
            json.dump(output, f, ensure_ascii=False, indent=2)
        print(f"[done] {len(records)}件を data_rootcoffee.json に出力しました"
              f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
