# -*- coding: utf-8 -*-
"""
scrape_ochishoten.py

越智商店(ochishoten.base.shop、愛媛県今治市国分6-4-22、自家焙煎豆の
オンライン販売)の商品情報を取得する。BASE。

【住所について】
実データ確認済み(2026-09時点): 公式ストアの特定商取引法ページ
(https://ochishoten.base.shop/law)で「〒799-1533 愛媛県今治市国分
6-4-22」と一致確認済み。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【非コーヒー豆商品の除外について】
実データ確認済み(2026-09-21再確認時点、全10件): 「水出しコーヒー2026
カッパラベル 1ℓ用」(水出し専用パック)・「【贈り物に】ドリップバッグ
３/５/１０個セット」(ドリップバッグ形態、計3件)が非対象。加えて、
NON_BEAN_KEYWORDSに含まれていなかったため見落とされていた
「ドリップバック７個セット」(「バッグ」ではなく「バック」表記のため
既存キーワードに非マッチ)・「越智商店オリジナル 豆缶」(保存缶)・
「珈琲縁日2025 巾着トートバッグ」「珈琲縁日2025 オリジナル手ぬぐい」
(グッズ)の4件も非コーヒー豆商品と判明したため、NON_BEAN_KEYWORDSに
追加した。残りはストレート/デカフェのコーヒー豆2件(いずれも150g固定)。

【flavor_notes(2026-09-21追記)】
実データ確認済み: og:descriptionに対象2件全てで産地スペック+
カッピングプロファイル(テイスティング要素)が入っている。末尾に
「※冷めたあとも、また味が変化しますので…」から始まる鮮度に関する
定型的な注意書きが続くため、この見出しの直前で打ち切る。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "越智商店",
    "url": "https://ochishoten.base.shop/",
    "platform": "BASE",
    "address": "愛媛県今治市国分6-4-22",
    "prefecture": "愛媛県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://ochishoten.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "水出しコーヒー", "ドリップバッグ", "ドリップバック", "豆缶", "トートバッグ", "手ぬぐい",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
FLAVOR_STOP_PATTERN = re.compile(r"※冷めたあとも")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    flavor_notes = desc_el["content"].strip() if desc_el and desc_el.get("content") else ""
    m = FLAVOR_STOP_PATTERN.search(flavor_notes)
    if m:
        flavor_notes = flavor_notes[:m.start()].strip()
    return {"title": title, "price": price, "flavor_notes": flavor_notes or None}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    records = []
    flavored_records = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        detail = build_record({
            "title": fields["title"],
            "price": fields["price"],
            "flavor_notes": fields.get("flavor_notes"),
            "url": product_url,
        })
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_ochishoten.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_ochishoten.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
