# -*- coding: utf-8 -*-
"""
scrape_cafedotoyo.py

三重東洋珈琲/ミンデン(cafedotoyo.base.shop、三重県松阪市郷津町163-5、
「ミンデン」ブランドの自家焙煎豆のオンライン販売。実店舗名はCAFE DO TOYO)
の商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品一覧の取得方法について】
実データ確認済み: sitemap.xml上32件の商品ページを個別に取得し、
og:title・product:price:amountのOGPメタタグから商品名・価格を取得する
(他のBASE系店舗と同じ方式)。重量違いの重複は無く(対象商品は全て200g)、
pick_canonical_items等のグルーピング処理は不要。

【MINDEN COFFEE POST(定期購入)について】
実データ確認済み: 同一BASEストア内に「MINDEN COFFEE POST（定期購入）」
という商品が存在する。商品説明を確認したところ「人気のオリジナルコーヒー
（200g）①バター焙煎ブレンド②ミンデンブレンド（①②を各月ごと順番に
お付けいたします）●月替わりの厳選コーヒー豆（100g）をセットにして
お届け」とあり、(a)既に単品としてカウント済みの銘柄を月替わりで
含む、(b)「厳選コーヒー豆」部分は月替わりで銘柄が特定できない、という
2点の理由から単品の銘柄情報としては扱えないため、他店舗の「おまかせ」
セットと同様の理由でNON_BEAN_KEYWORDSの「定期購入」により除外する。

【非コーヒー豆商品の除外について】
実データ確認済み(全32件): 以下がコーヒー豆単品ではないため
NON_BEAN_KEYWORDSで除外する。
  - 「◯◯（5袋）」「ディップスタイルコーヒーギフト（10/24/36袋）」等の
    個包装ドリップ/ディップ形式(「袋」を含む)→「袋」
  - 「DIP style coffee(10個)」(半角括弧の個数表記)→「個)」
  - 「NEWバター焙煎ブレンドコーヒー」: タイトルだけでは判別しにくいが、
    商品説明で「ドリップコーヒー 5個入り」と明記されたドリップバッグの
    リニューアル品と確認済み→「ブレンドコーヒー」(この店の実際の焙煎豆
    商品はすべて「◯◯ブレンド（200g）」のように末尾が「ブレンド」で
    終わり「ブレンドコーヒー」という語順は使わないため誤除外しない)
  - 「ドリップ&ディップSET」「ドリップコーヒーギフト...」→「ドリップ」
  - 「カフェオレベース...」(液体)→「カフェオレベース」
  - 「◯◯ギフト（...）」→「ギフト」
  - 「MINDEN COFFEE POST（定期購入）」→「定期購入」
  - 「水だしアイスコーヒー(夏限定)」(水出し専用パック、1パック入り)→「水だし」
なお「インドアラビカアイスコーヒー（200g）」「ミンデンショコラ(200g)」は
商品説明を確認したところ、いずれも実際に焙煎した豆売り商品(前者はアイス
コーヒー用に深煎りした豆、後者は「チョコレートの味がするわけではない」と
明記されたカカオ香を思わせる深煎り豆)と確認できたため対象に含める。
残り17件を対象とする。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "三重東洋珈琲(ミンデン)",
    "url": "https://cafedotoyo.base.shop/",
    "platform": "BASE",
    "address": "三重県松阪市郷津町163-5",
    "prefecture": "三重県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://cafedotoyo.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "袋", "個)", "ブレンドコーヒー", "ドリップ", "カフェオレベース", "ギフト",
    "定期購入", "水だし",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(product_url: str, fields: dict) -> dict | None:
    title = fields["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": fields["price"],
            "product_url": product_url,
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": fields["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": product_url,
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record(product_url, fields)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_cafedotoyo.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_cafedotoyo.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
