# -*- coding: utf-8 -*-
"""
scrape_nakayamacoffee.py

中山コーヒー園(forestcoffee.official.ec、沖縄県名護市中山378)の商品情報を
取得する。official.ecはBASEプラットフォームのファミリードメイン。BASE。
自ら栽培した沖縄産コーヒーを海外産豆とブレンドして自家焙煎する農園直営ショップ。

【住所について】
特定商取引法ページ(https://forestcoffee.official.ec/law)で実際に確認したところ
「事業者の名称: 由居大周 / 事業者の所在地: 〒905-0004 沖縄県名護市中山378」で
あることを確認した(2026-09時点)。候補リストの住所と一致。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品について】
実データ確認済み(全12件): 自家栽培の沖縄県産コーヒー豆を海外産の豆と
ブレンドした2種類のコーヒー豆(【海風】=中山コーヒー園×エチオピア・
コロンビア・ルワンダ、【森風】=中山コーヒー園×グアテマラ・ブラジル、
og:descriptionで実データ確認済み)のみが対象。商品名に「ブレンド」を含む
ため、coffee_parserのBLEND_KEYWORDSでcategory="ブレンド"と自動判定される
(複数産地の混合のためorigin_countryは特定せずnullのまま)。

【非コーヒー豆商品の除外について】
実データ確認済み(全12件): コーヒーチェリー(果実)の茶・コーヒーリーフ
(葉)の茶(カスカラ珈琲含む、いずれも焙煎豆ではなくハーブティー的な別商品)・
ドリップコーヒー(個包装×5個、豆ではなくドリップバッグ形態)・定期便(リーフ
ティーの定期購入)・【海風】【森風】100gセット(2種の詰め合わせセット、
単品2件と重複するため除外)がNON_BEAN_KEYWORDSで除外される。残り2件
(【海風】【森風】各100g)を対象とする。
"""

import json
import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "中山コーヒー園",
    "url": "https://forestcoffee.official.ec/",
    "platform": "BASE",
    "address": "沖縄県名護市中山378",
    "prefecture": "沖縄県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://forestcoffee.official.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

# 実データ確認済み(理由はdocstring参照)
NON_BEAN_KEYWORDS = ["茶", "カスカラ", "ドリップコーヒー", "セット", "定期便", "リーフティ"]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record({"title": fields["title"], "price": fields["price"], "url": product_url})
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_nakayamacoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_nakayamacoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
