# -*- coding: utf-8 -*-
"""
scrape_hiraokacoffee.py

平岡珈琲店(hiraokacoffe.thebase.in、大阪市中央区瓦町、大正10年(1921年)
創業の老舗喫茶・自家焙煎珈琲店。公式サイトはcafe-hiraoka.jp)の商品情報を
取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【注記】この店のBASEショップの特定商取引法ページには運営者の住所として
BASE株式会社(東京都港区)の代理表記があり、店舗自身の住所は開示されて
いない。SHOP_INFOの住所は公式サイト(cafe-hiraoka.jp、大阪市中央区瓦町の
老舗喫茶店であることを明記)から採用した。

【商品ラインナップについて】
実データ確認済み: オンライン販売の主力は看板ブレンド「百年珈琲」1銘柄
のみで、これが100g(豆/挽き)・100g×2袋セット・100g×4袋セットの計4商品
として登録されている。商品名の「｜」より前を基準名としてグルーピング
し、重量表記(×N袋の乗算を含む)が最小のもの(100g)を代表として採用する。
100g同士で豆/挽きが並ぶ場合は「豆」を優先する。

【非コーヒー豆商品の除外について】
実データ確認済み: 百年珈琲(ドリップパック)(個包装フォーマット)・
焼きドーナツ/シナモンティードーナツ(100周年記念の菓子、コーヒー豆
ではない)が非対象。NON_BEAN_KEYWORDSで除外する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "平岡珈琲店",
    "url": "https://www.cafe-hiraoka.jp/",
    "platform": "BASE",
    "address": "大阪府大阪市中央区瓦町3丁目6-11",
    "prefecture": "大阪府",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://hiraokacoffe.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["ドリップパック", "ドーナツ"]
WEIGHT_MULT_PATTERN = re.compile(r"(\d+)g\s*[×xX]\s*(\d+)")
WEIGHT_PATTERN = re.compile(r"(\d+)g")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def weight_in_grams(title: str) -> int | None:
    m = WEIGHT_MULT_PATTERN.search(title)
    if m:
        return int(m.group(1)) * int(m.group(2))
    m2 = WEIGHT_PATTERN.search(title)
    return int(m2.group(1)) if m2 else None


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = item["title"].split("｜")[0].strip()
        weight = weight_in_grams(item["title"])
        weight_key = weight if weight is not None else float("inf")
        grind_key = 0 if "豆" in item["title"] else (1 if "挽き" in item["title"] else 0)
        existing = by_base_name.get(base_name)
        if existing is None:
            by_base_name[base_name] = item
            continue
        existing_weight = weight_in_grams(existing["title"])
        existing_weight_key = existing_weight if existing_weight is not None else float("inf")
        existing_grind_key = 0 if "豆" in existing["title"] else (1 if "挽き" in existing["title"] else 0)
        if (weight_key, grind_key) < (existing_weight_key, existing_grind_key):
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_g = weight_in_grams(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_hiraokacoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_hiraokacoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
