# -*- coding: utf-8 -*-
"""
scrape_ijiricoffee.py

井尻珈琲焙煎所(ijiricoffee.thebase.in、大阪市大正区三軒家東1-4-11、
自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

住所は特定商取引法に基づく表記ページ(https://ijiricoffee.thebase.in/law)
の「事業者の所在地」欄(〒551-0002 大阪府大阪市大正区三軒家東1-4-11)で
確認。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品ラインナップについて】
実データ確認済み: sitemap.xmlに掲載されている商品は全4件のみで、
「日々の珈琲（春/夏/秋/冬）select」という季節ごとに異なる銘柄の
ブレンドが、それぞれ異なる内容量(100g×2/200g×2/100g×4/200g×4)で
個別に販売されている。季節名が異なるため銘柄自体が別物であり、
重量違いによる重複(同一銘柄の別サイズ展開)ではないため、重複排除は
行わない。商品名の「N g × M」表記から乗算して総重量を算出する
(hiraokacoffee.pyと同じ方式)。

【非コーヒー豆商品の除外について】
実データ確認済み: 4件全てがコーヒー豆(ブレンド)で、NON_BEAN_KEYWORDS
に該当する商品は無し。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "井尻珈琲焙煎所",
    "url": "https://ijiricoffee.thebase.in/",
    "platform": "BASE",
    "address": "大阪府大阪市大正区三軒家東1-4-11",
    "prefecture": "大阪府",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://ijiricoffee.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS: list[str] = []
WEIGHT_MULT_PATTERN = re.compile(r"(\d+)\s*[gｇ]\s*[×xX]\s*(\d+)")
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def weight_in_grams(title: str) -> int | None:
    m = WEIGHT_MULT_PATTERN.search(title)
    if m:
        return int(m.group(1)) * int(m.group(2))
    m2 = WEIGHT_PATTERN.search(title)
    return int(m2.group(1)) if m2 else None


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_g = weight_in_grams(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record({"title": fields["title"], "price": fields["price"], "url": product_url})
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_ijiricoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_ijiricoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
