# -*- coding: utf-8 -*-
"""
scrape_nikkocoffee.py

日光珈琲 Nikko Coffee(nikkocoffee.thebase.in、栃木県鹿沼市上材木町1739
〈運営元:有限会社風間総合サービス〉、自家焙煎豆のオンライン販売)の商品情報を
取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【非コーヒー豆商品の除外について】
実データ確認済み: 全78件のうちドリップバックコーヒー・ギフトセット・
お試しセット(いずれもブレンド1杯分の詰め合わせ)・コーヒービーンズケーキ・
タンブラー/マグ等の什器・リキッドアイスコーヒー・カフェオレベース
「珈琲シラツプ」・各種シロップ/コンフィチュール(ジャム)・スコーン/パン
セット・黒カレー・自家焙煎体験キット「ばいせんくん」・生豆(自宅焙煎用の
未焙煎豆、既に焙煎豆として販売済みの銘柄と重複)・トラベルガイドブック・
ステッカー、および「コピー：」接頭辞が付いた重複SKU1件が非対象。
NON_BEAN_KEYWORDSで除外する。

【重量違いの重複について】
実データ確認済み: 焙煎豆は「(銘柄名)｜200g コーヒー豆【ロースト度】」
「(銘柄名)｜お得な500g コーヒー豆【ロースト度】」「(銘柄名)｜もっと
お得な1kg コーヒー豆【ロースト度】」の3形態(一部銘柄は200gのみ)で
個別商品登録されている。商品名の"｜"より前を基準名としてグルーピングし、
最小重量(200g)を代表として採用する。

【全角/半角スペース表記ゆれによる重複排除漏れについて】
実データ確認済み(初回実行で発覚): 「タンザニア キリマンジャロ」(200g版、
銘柄間が半角スペース)と「タンザニア　キリマンジャロ」(500g版、銘柄間が
全角スペース)のように、同一銘柄でも200g版と500g版で"｜"より前の
基準名の空白文字が半角/全角で表記ゆれしており、素の文字列一致では
別銘柄と誤判定され両方とも残ってしまう不具合があった(アスロン
コーヒー焙煎所のグアテマラと同種のバグ)。WHITESPACE_PATTERNで空白を
正規化してから基準名を比較するよう修正した。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "日光珈琲",
    "url": "https://nikkocoffee.thebase.in/",
    "platform": "BASE",
    "address": "栃木県鹿沼市上材木町1739",
    "prefecture": "栃木県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://nikkocoffee.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ドリップバック", "ギフトセット", "お試しセット", "BEANS CAKE", "タンブラー", "マグ",
    "リキッドアイスコーヒー", "カフェオレベース", "シラツプ", "シロップ", "コンフィチュール",
    "スコーン", "パンセット", "黒カレー", "ばいせんくん", "自家焙煎体験キット", "生豆",
    "ガイドブック", "ステッカー", "コピー：",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*(kg|g|ｋｇ|ｇ)", re.IGNORECASE)
WHITESPACE_PATTERN = re.compile(r"[\s　]+")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def parse_weight_g(title: str) -> int | None:
    m = WEIGHT_PATTERN.search(title)
    if not m:
        return None
    num = int(m.group(1))
    unit = m.group(2).lower()
    return num * 1000 if unit in ("kg", "ｋｇ") else num


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WHITESPACE_PATTERN.sub(" ", item["title"].split("｜")[0]).strip()
        weight_key = item["weight_g"] if item["weight_g"] is not None else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight = existing["weight_g"] if existing and existing["weight_g"] is not None else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": item["weight_g"],
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "weight_g": parse_weight_g(fields["title"]),
        })

    canonical_items = pick_canonical_items(all_items)
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for item in canonical_items:
        prev = previous.get(item["url"])
        if is_unchanged(prev, raw_name=item["title"]):
            records.append(prev)
            continue

        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_nikkocoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_nikkocoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
