# -*- coding: utf-8 -*-
"""
scrape_sohcoffee.py

スペシャルティコーヒー蒼～soh～(soh-coffee.com、sohcoffee.thebase.inの
オンライン販売、愛知県豊川市本野ケ原1-35、豊橋・豊川に複数拠点を持つ
自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量バリエーションについて】
実データ確認済み: 他のBASE店舗(kamecoffee等)のように重量違いを複数の
商品ページに分割する方式ではなく、1商品ページ内にBASEの「商品バリエーション」
セレクトボックスとして「100g」(基準)・「お得パック500g」・「お得セット2kg」
という重量帯を持たせる方式(価格は基準100gからの割引後総額表示)。og:titleと
product:price:amountのmetaタグは常に最初のバリエーション(=100g)の情報を
反映するため、通常のBASEテンプレートと同じmeta抽出だけで100g代表の価格は
取得できるが、weight_gは別途ページ本文の<option>要素群から重量表記を含む
テキストを検出し最小値(100g)を採用する(kg表記は×1000してg換算)。
実データ確認済み(2026-09再確認): [オーダー焙煎]のパナマ ゲイシャのみ
例外で、商品バリエーションが重量帯ではなく豆/挽き方(豆のまま・中挽き等)の
みのため<option>群に重量表記が一切現れない。この場合は商品名自体に
埋め込まれた重量表記(タイトル末尾の"...200g...")をフォールバックとして
使用する。

【非コーヒー豆商品の除外について】
実データ確認済み(全86件): タンブラー・コーヒー豆キャニスター・コーヒー
ギフトセット各種・ドリップコーヒー/ドリップバッグ各種(ギフト・プチギフト
含む)・カフェオレベース・アイスコーヒーリキッド(ボトル)・コーヒー豆
定期便/サブスクリプションサービス・コーヒー豆３種セット・[メール便]小口
パック(各種コーヒー豆の詰め合わせで単一銘柄を特定できない)・TOYOKAWA
YUTAKA COFFEE(全形態がドリップバッグ)・コールドブリューコーヒーバッグが
非対象。NON_BEAN_KEYWORDSで除外する。[オーダー焙煎]のパナマ ゲイシャ等は
単一銘柄のカスタム焙煎注文のため対象に含める。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "スペシャルティコーヒー蒼～soh～",
    "url": "https://soh-coffee.com/",
    "platform": "BASE",
    "address": "愛知県豊川市本野ケ原1-35",
    "prefecture": "愛知県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://sohcoffee.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "タンブラー", "キャニスター", "ギフト", "ドリップ", "カフェオレベース",
    "アイスコーヒーリキッド", "定期便", "サブスク", "セット", "小口パック",
    "TOYOKAWA YUTAKA", "コールドブリュ",
]
WEIGHT_G_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
WEIGHT_KG_PATTERN = re.compile(r"(\d+)\s*[kKｋＫ][gｇ]")
OPTION_TEXT_PATTERN = re.compile(r"<option[^>]*>([^<]*)</option>")


def fetch_page(url: str) -> tuple[BeautifulSoup, str]:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser"), resp.text


def fetch_sitemap_urls() -> list[str]:
    soup, _ = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def extract_min_variant_weight_g(html: str) -> int | None:
    """理由はモジュールdocstring参照(重量帯はページ本文の<option>群にのみ
    現れ、商品名やmetaタグには含まれない)。最小重量(=基準100g)を採用する。"""
    weights = []
    for m in OPTION_TEXT_PATTERN.finditer(html):
        text = m.group(1)
        km = WEIGHT_KG_PATTERN.search(text)
        if km:
            weights.append(int(km.group(1)) * 1000)
            continue
        gm = WEIGHT_G_PATTERN.search(text)
        if gm:
            weights.append(int(gm.group(1)))
    return min(weights) if weights else None


def build_record(item_url: str, soup: BeautifulSoup, html: str) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None

    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    weight_g = extract_min_variant_weight_g(html)
    if weight_g is None:
        # 理由はモジュールdocstring参照([オーダー焙煎]商品は重量帯の
        # <option>を持たず豆/挽き方の<option>のみのため、商品名自体に
        # 埋め込まれた重量表記(例: "...ゲイシャ ウォッシュド 200g...")を
        # フォールバックとして採用する(実データ確認済み: 全26件中1件が該当)
        km = WEIGHT_KG_PATTERN.search(title)
        if km:
            weight_g = int(km.group(1)) * 1000
        else:
            gm = WEIGHT_G_PATTERN.search(title)
            if gm:
                weight_g = int(gm.group(1))

    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": price,
            "product_url": item_url,
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": price,
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item_url,
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    item_urls = fetch_sitemap_urls()

    records = []
    flavored_records = []
    for item_url in item_urls:
        try:
            soup, html = fetch_page(item_url)
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {item_url} ({e})")
            continue
        detail = build_record(item_url, soup, html)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_sohcoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_sohcoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
