# -*- coding: utf-8 -*-
"""
scrape_ciaoppe.py

チャオッペ(ciaoppe.buyshop.jp、大阪市旭区清水5-12-12、自家焙煎豆の
オンライン販売)の
商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量違いの重複について】
実データ確認済み: エスプレッソ用の2銘柄(クレマ極厚エスプレッソブレンド・
ラテアートしやすいエスプレッソブレンド)が通常200gと【大容量】1kgの
2サイズで、後者は「再入荷」「【在庫限り】」等の接頭辞付きでも登録されて
いるため、先頭の【】括弧書き・「再入荷」を除去してから重量でグルーピング
し、最小重量(200g)を代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み: ギフト各種(BOX・カフェオレベース・ドリップバッグ)・
カフェオレベース単体・ドリップバッグコーヒー各種(個包装フォーマット)・
水出しコーヒーパック(液体抽出用パック)・業務用コーヒー豆1kg単位定期便・
定期便送料無料シリーズ(通常ラインナップと同一銘柄の定期便まとめ買い枠)・
はじまりのセット/飲み比べセット(複数銘柄の詰め合わせで単一銘柄と特定
できない)・コルクコースター(器具)・トントンコーヒー(専用パック製品で
通常の豆売りと異なるフォーマット)が非対象。NON_BEAN_KEYWORDSで除外する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "チャオッペ",
    "url": "https://ciaoppe.buyshop.jp/",
    "platform": "BASE",
    "address": "大阪府大阪市旭区清水5-12-12",
    "prefecture": "大阪府",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://ciaoppe.buyshop.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ギフト", "カフェオレベース", "ドリップバッグ", "ドリップバック", "水出し",
    "業務用", "定期便", "はじまりのセット", "飲み比べセット", "コルクコースター",
    "トントンコーヒー",
]
PREFIX_PATTERN = re.compile(r"^(【[^】]*】|再入荷)+")
WEIGHT_PATTERN = re.compile(r"(\d+(?:\.\d+)?)\s*(kg|ｋｇ|[gｇ])", re.IGNORECASE)


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def weight_in_grams(text: str) -> int | None:
    m = WEIGHT_PATTERN.search(text)
    if not m:
        return None
    value = float(m.group(1))
    unit = m.group(2).lower()
    if unit in ("kg", "ｋｇ"):
        value *= 1000
    return int(value)


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    raw_title = title_el["content"].split(" | ")[0].strip()
    if not raw_title or any(kw in raw_title for kw in NON_BEAN_KEYWORDS):
        return None
    title = PREFIX_PATTERN.sub("", raw_title).strip()
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_key = weight_in_grams(item["title"]) or float("inf")
        existing = by_base_name.get(base_name)
        existing_weight = weight_in_grams(existing["title"]) if existing else None
        existing_weight = existing_weight if existing_weight is not None else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_g = weight_in_grams(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        prev = previous.get(item["url"])
        if is_unchanged(prev, raw_name=item["title"]):
            records.append(prev)
            continue
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_ciaoppe.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_ciaoppe.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
