# -*- coding: utf-8 -*-
"""
scrape_mizutama.py

瑞玉珈琲(mizu0coffee.base.shop、栃木県那須郡那須町高久乙594-81、自家焙煎豆の
オンライン販売)の商品情報を取得する。BASE(白ラベルドメイン)。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【非コーヒー豆商品の除外について】
実データ確認済み: 全12件すべてが単一農園/産地のストレートコーヒー
(デカフェ3種を含む)で、非対象商品は無い。重量表記も商品名に無く
単一サイズ販売のため重量重複処理は不要。

【flavor_notes(2026-09-21追記)】
実データ確認済み: og:descriptionにテイスティング文が直接入っている
(対象12件全て確認、うち1件は産地スペック情報のみでテイスティング語を
含まないがそのまま採用する)。一部商品には「おすすめ焙煎度　ハイ
浅煎り←□□■□□→深煎り」という店舗共通の焙煎度合い図(前後どちらの
位置に挿入されるかは商品によって不定)、「味覚レベル」に続く★評価欄、
「珈琲豆　コーヒー豆…」のような繰り返しキーワード/ハッシュタグの
スパム的文言、「豆のままの販売になります。」「コメントいただければ
粉にもできます。」という定型注意書きが混入するため、これらを除去する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "瑞玉珈琲",
    "url": "https://mizu0coffee.base.shop/",
    "platform": "BASE",
    "address": "栃木県那須郡那須町高久乙594-81",
    "prefecture": "栃木県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://mizu0coffee.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

DIAGRAM_PATTERN = re.compile(r"おすすめ焙煎度[\s　]*\S*[\s　]*浅煎り←[□■\s　]*→深煎り")
RATING_STOP_PATTERN = re.compile(r"味覚レベル")
KEYWORD_SPAM_PATTERN = re.compile(r"#?(?:珈琲豆|コーヒー豆|コーヒー)(?:[\s　]*#?(?:珈琲豆|コーヒー豆|コーヒー)){2,}")
NO_GRIND_NOTICE_PATTERN = re.compile(r"豆のままの販売になります。|コメントいただければ粉にもできます。")


def extract_flavor_notes(description: str | None) -> str | None:
    """理由はモジュールdocstring参照。"""
    if not description:
        return None
    text = DIAGRAM_PATTERN.sub("", description)
    m = RATING_STOP_PATTERN.search(text)
    if m:
        text = text[: m.start()]
    m = KEYWORD_SPAM_PATTERN.search(text)
    if m:
        text = text[: m.start()]
    text = NO_GRIND_NOTICE_PATTERN.sub("", text)
    return text.strip() or None


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    flavor_notes = extract_flavor_notes(desc_el["content"]) if desc_el and desc_el.get("content") else None
    return {"title": title, "price": price, "flavor_notes": flavor_notes}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": None,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "flavor_notes": fields.get("flavor_notes"),
        })
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_mizutama.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_mizutama.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
