# -*- coding: utf-8 -*-
"""
scrape_jinnosuke.py

仁之助コーヒー(jinnosuke.official.ec、滋賀県近江八幡市、自家焙煎豆の
オンライン販売)の商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【非コーヒー豆商品の除外について】
実データ確認済み(sitemap.xml掲載の全11件): 「伊賀流ジビエ　ペットジャーキー」
(ペット用おやつ、コーヒーと無関係)、および「ニホンノキレイ」「ニホンノ
スコヤカ」「ニホンノヌクモリ」の3件(商品詳細ページのog:descriptionを
確認したところ、いずれもヨモギ・クロモジ等を使ったハーブブレンド茶
(6包入り)で、コーヒー豆ではない)が非対象。固有名詞のため商品名からの
一般的なキーワード判定ができず、個別に列挙して除外する。残り7件
(スペシャルティコーヒー【堀】【山】【虹】【月】【陽】、いずれも100g)を
対象とする。

【重量について】
実データ確認済み: 対象7件はいずれも100g単品のみで、重量違いの重複は
無い。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "仁之助コーヒー",
    "url": "https://jinnosuke.official.ec/",
    "platform": "BASE",
    "address": "滋賀県近江八幡市新町一丁目29",
    "prefecture": "滋賀県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://jinnosuke.official.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

# 実データ確認済み(商品詳細ページのog:descriptionより): いずれもコーヒーと
# 無関係な固有名詞のため、一般的なキーワードではなく個別に列挙して除外する。
NON_BEAN_KEYWORDS = [
    "ジャーキー", "ニホンノキレイ", "ニホンノスコヤカ", "ニホンノヌクモリ",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
ROAST_HINT_TERMS = ["中深煎り", "中浅煎り", "極深煎り", "浅煎り", "中煎り", "深煎り"]


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def extract_roast_hint(title: str) -> str | None:
    for term in ROAST_HINT_TERMS:
        if term in title:
            return term
    return None


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "roast_hint": extract_roast_hint(title),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    records = []
    flavored_records = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        detail = build_record({"title": fields["title"], "price": fields["price"], "url": product_url})
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_jinnosuke.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_jinnosuke.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
