# -*- coding: utf-8 -*-
"""
scrape_mondial328.py

MONDIAL KAFFEE 328(mondial328.theshop.jp、大阪市西区南堀江1-1-20、
自家焙煎豆のオンライン販売)の商品情報を取得する。大阪市内に複数店舗を
展開しているが5店舗前後で規模基準内。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量表記の位置について】
実データ確認済み: 他のBASE系店舗と異なり、商品名の先頭に重量が
「30g」「100g」「250g」「500g」の形で付与されている(例:
「100g AUTUMN BLEND(中深煎り)」)。先頭の重量トークンを除いた残りを
基準名としてグルーピングし、最小重量(30g、テイスター向けの少量規格)を
代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み: DRIP BAG各種(5-PACK BOX・1 pack、いずれも個包装
フォーマット)・BOTTOLED COFFEE 250ml(瓶入り液体)・有田焼 ORIGINAL
ICED DRINK CUP(器具)が非対象。NON_BEAN_KEYWORDSで除外する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "MONDIAL KAFFEE 328",
    "url": "https://mondial328.theshop.jp/",
    "platform": "BASE",
    "address": "大阪府大阪市西区南堀江1-1-20",
    "prefecture": "大阪府",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://mondial328.theshop.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["DRIP BAG", "BOTTOLED COFFEE", "ICED DRINK CUP"]
LEADING_WEIGHT_PATTERN = re.compile(r"^(\d+)\s*g\s+", re.IGNORECASE)


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        m = LEADING_WEIGHT_PATTERN.match(item["title"])
        weight_key = int(m.group(1)) if m else float("inf")
        base_name = LEADING_WEIGHT_PATTERN.sub("", item["title"]).strip()
        existing = by_base_name.get(base_name)
        if existing is None:
            by_base_name[base_name] = item
            continue
        existing_m = LEADING_WEIGHT_PATTERN.match(existing["title"])
        existing_weight = int(existing_m.group(1)) if existing_m else float("inf")
        if weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    m = LEADING_WEIGHT_PATTERN.match(title)
    weight_g = int(m.group(1)) if m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        prev = previous.get(item["url"])
        if is_unchanged(prev, raw_name=item["title"]):
            records.append(prev)
            continue
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_mondial328.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_mondial328.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
