# -*- coding: utf-8 -*-
"""
scrape_funaki.py

舟木コーヒー(funakicoffee.theshop.jp、〒085-0021 北海道釧路市浪花町9-3、
自家焙煎豆のオンライン販売)の商品情報を取得する。theShop(BASE系)。

robots.txt確認済み(2026-09時点): 他のtheShop/BASE系店舗と同一の記述
("Generated by GRP")。python-requests/curl等は個別にDisallow: /指定が
あるが、User-agent: *ルールでは実質許可。本スクレイパーは識別可能な
独自User-Agentを使用する。

住所は特定商取引法に基づく表記にて実データ確認済み: 「北海道釧路市浪花町
9-3」、電話番号0154-22-4383(候補リストの住所と一致)。

【商品一覧の取得方法について】
実データ確認済み(2026-09時点、全26件): sitemap.xmlに列挙された/items/N
形式のURLを起点とする。

【非コーヒー豆商品の除外について】
実データ確認済み: ギフトボックス(250g×2個入等)・ドリップバッグ(1袋/
複数種アソート、単一銘柄でない)・カフェラテベース(液体)・水出し
コーヒーパック(液体抽出用)が非対象。NON_BEAN_KEYWORDSで除外する。

【重量違いの重複について】
実データ確認済み: 定番ブレンド1種(ウェットランドブレンド)・シングル
オリジン5種・デカフェ1種の計7銘柄が100g/250gの2サイズで個別商品登録
されている。商品名末尾の重量を除いた基準名でグルーピングし、最小重量
(100g)を代表として採用する。

【flavor_notes(2026-09-21追記)】
実データ確認済み: og:descriptionに対象7件全てでテイスティング文が
入っている。うち6件は末尾に「※発送は「ヤマト宅急便」または「ゆう
パック」…」という配送案内の定型文が続くため、この見出しの直前で
打ち切る。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "舟木コーヒー",
    "url": "https://funakicoffee.theshop.jp/",
    "platform": "theShop(BASE系)",
    "address": "北海道釧路市浪花町9-3",
    "prefecture": "北海道",
    "robots_txt_status": "実質許可(2026-09確認。他のtheShop/BASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://funakicoffee.theshop.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["ギフト", "ドリップバッグ", "カフェラテベース", "水出し"]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
WEIGHT_TOKEN_PATTERN = re.compile(r"[（(]\s*\d+\s*[gｇ]\s*[）)]")
FLAVOR_STOP_PATTERN = re.compile(r"※発送は")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    resp.encoding = "utf-8"
    return BeautifulSoup(resp.text, "html.parser")


def fetch_product_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    flavor_notes = desc_el["content"].strip() if desc_el and desc_el.get("content") else ""
    m = FLAVOR_STOP_PATTERN.search(flavor_notes)
    if m:
        flavor_notes = flavor_notes[:m.start()].strip()
    return {"title": title, "price": price, "flavor_notes": flavor_notes or None}


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_TOKEN_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_product_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({
            "title": fields["title"],
            "price": fields["price"],
            "flavor_notes": fields.get("flavor_notes"),
            "url": product_url,
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_funaki.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_funaki.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
