# -*- coding: utf-8 -*-
"""
scrape_sansyokouji.py

COFFEE山椒小路(ec.sansyokouji.shop、〒998-0043 山形県酒田市本町2-3-2、
自家焙煎豆のオンライン販売)の商品情報を取得する。BASE(独自ドメイン)。

【STORES.jpからの移転について】
候補リスト作成時点ではsansyokoujinet.stores.jpというSTORES.jp店舗として調査
されていたが、実データ確認(2026-09時点)したところ、同店は「オンラインショップ
移転のお知らせ」を掲示しており、2026年2月11日付でhttps://ec.sansyokouji.shop/
という新しいショップに完全移転済みだった。新ショップの実データ確認では
robots.txt・sitemap.xml・フッターの「powered by BASE」表記等からBASE(独自ドメイン)
であることを確認済みのため、STORES.jp対象外ルール(GitHub Actionsブロック)には
該当せず、通常のBASEスクレイパーとして実装する。旧sansyokoujinet.stores.jpは
参照しない。

【住所について】
新ショップのフッターで実データ確認(2026-09時点): 〒998-0043 山形県酒田市本町2-3-2。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by GRP")。
curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *ルールでは
実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品一覧・除外商品について】
sitemap.xmlから/items/を含むURLを列挙する方式(瑞玉珈琲と同じ)。実データ確認済み
(2026-09時点): 「注文焙煎　200g」(豆やブレンドを指定して都度焙煎する特注品で、
固定の銘柄・産地を持たないオーダーメイド商品)が1件混在しており、キーワード
除外(NON_BEAN_KEYWORDS)で対象外とする。

【flavor_notes(テイスティングノート)について(2026-09-20追記)】
実データ確認済み(全34商品): 他のBASE系店舗と共通の「item-detail_description」
系クラスではなく、より新しいテーマのdiv.item-detail__descに店主による
具体的な風味描写がある。以前はog:title/価格のみ取得し、この要素自体を
一切読んでいなかった。og:description(メタタグ)にも同内容が入っているが
長文で切り詰められる可能性があるため、div側から直接取得する。末尾に
「※」で始まる注記が付く可能性を考慮してその手前までを採用する。
"""

import re
import unicodedata

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "COFFEE山椒小路",
    "url": "https://ec.sansyokouji.shop/",
    "platform": "BASE",
    "address": "山形県酒田市本町2-3-2",
    "prefecture": "山形県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://ec.sansyokouji.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
# 理由はモジュールdocstring参照(オーダーメイドの注文焙煎は固定銘柄の商品でない)
NON_BEAN_KEYWORDS = ["注文焙煎", "ギフト", "セット"]
FLAVOR_STOP_PATTERN = re.compile(r"^※")


def parse_flavor_notes(soup: BeautifulSoup) -> str | None:
    """理由はモジュールdocstring参照。"""
    el = soup.select_one("div.item-detail__desc")
    if not el:
        return None
    lines = []
    for raw_line in el.get_text(separator="\n").split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        if FLAVOR_STOP_PATTERN.match(line):
            break
        lines.append(line)
    return "".join(lines) or None


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    # 実データ確認済み(2026-09時点): 一部商品のog:titleにタブ文字が含まれる
    # (例:「パリの朝市\t100g」)ため、空白類を単一の半角スペースに正規化する
    title = re.sub(r"\s+", " ", unicodedata.normalize("NFKC", title)).strip()
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict, flavor_notes: str | None = None) -> dict | None:
    title = item["title"]
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "non_bean": True,
            "product_url": item["url"],
        }

    parsed = parse_product(title)
    weight_m = WEIGHT_PATTERN.search(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "flavor_notes": flavor_notes,
        "price": item["price"],
        "weight_g": int(weight_m.group(1)) if weight_m else None,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    non_bean_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            soup = fetch_page(product_url)
            fields = extract_og_fields(soup)
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record(
            {"title": fields["title"], "price": fields["price"], "url": product_url},
            parse_flavor_notes(soup),
        )
        if detail is None:
            continue
        if detail.get("non_bean"):
            non_bean_records.append(detail)
        elif detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records, non_bean_records


if __name__ == "__main__":
    import json

    records, flavored_records, non_bean_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
        "non_bean_products_excluded": non_bean_records,
    }
    with open("data_sansyokouji.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_sansyokouji.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件、"
          f"非コーヒー豆{len(non_bean_records)}件は別枠に分離)")
