# -*- coding: utf-8 -*-
"""
scrape_mametabito.py

珈琲工房まめたびと（豆旅人）(mametabito.official.ec、〒960-1107 福島県福島市上鳥渡字
寺北18-2敷地内、自家焙煎豆のオンライン販売。運営者:高橋亨)の商品情報を取得する。BASE。

【住所について】
公式サイトの特定商取引法ページ(https://mametabito.official.ec/law)で実データ確認
(2026-09時点): 〒960-1107 福島県福島市上鳥渡字寺北18ー２敷地内。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by GRP")。
curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *ルールでは
実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品一覧について】
sitemap.xmlから/items/を含むURLを列挙する方式(瑞玉珈琲と同じ)。実データ確認済み
(2026-09時点): 24件。商品名に重量(100g/250g)が明記されているため、正規表現で
抽出する。

【flavor_notes(2026-09-20追記)】
実データ確認済み: og:descriptionの先頭に実際のテイスティング・商品紹介文が
あり、その後に必ず「焙煎度合い　<ロースト表記>豆の状態でお送り致します。」
という店舗共通の発送方法定型文が続く(シングルオリジン商品はさらに「銘柄の
変更を行う場合がございます」という注意書きが続く)。この定型文の直前までを
flavor_notesとして採用する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "珈琲工房まめたびと（豆旅人）",
    "url": "https://mametabito.official.ec/",
    "platform": "BASE",
    "address": "福島県福島市上鳥渡字寺北18-2敷地内",
    "prefecture": "福島県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://mametabito.official.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
NON_BEAN_KEYWORDS = ["ギフト", "セット", "ドリップバッグ"]
FLAVOR_STOP_PATTERN = re.compile(r"焙煎度合い")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_flavor_notes(description: str | None) -> str | None:
    """理由はモジュールdocstring参照。"""
    if not description:
        return None
    m = FLAVOR_STOP_PATTERN.search(description)
    text = description[:m.start()] if m else description
    return text.strip() or None


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    description = desc_el["content"] if desc_el and desc_el.get("content") else None
    return {"title": title, "price": price, "description": description}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "non_bean": True,
            "product_url": item["url"],
        }

    parsed = parse_product(title)
    weight_m = WEIGHT_PATTERN.search(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": extract_flavor_notes(item.get("description")),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": int(weight_m.group(1)) if weight_m else None,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    non_bean_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record({
            "title": fields["title"], "price": fields["price"],
            "description": fields.get("description"), "url": product_url,
        })
        if detail is None:
            continue
        if detail.get("non_bean"):
            non_bean_records.append(detail)
        elif detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records, non_bean_records


if __name__ == "__main__":
    import json

    records, flavored_records, non_bean_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
        "non_bean_products_excluded": non_bean_records,
    }
    with open("data_mametabito.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_mametabito.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件、"
          f"非コーヒー豆{len(non_bean_records)}件は別枠に分離)")
