# -*- coding: utf-8 -*-
"""
scrape_mokuren.py

珈琲もくれん(mokuren.official.ec、〒640-8125 和歌山市島崎町3-27、
自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

【「電話/FAX/メール注文のみ」という店舗説明との整合性について】
当初は候補リストで「じゃんじゃん横丁の店舗で電話/FAX/メール注文のみ」
と説明されていたため手動入力(manual)を想定していたが、実際に
mokuren.official.ec のrobots.txtを確認したところ「Generated by GRP」
(=BASE)の標準的な記述であり、sitemap.xmlには実売中の商品ページ
(/items/N、125件)が現に存在し、商品ページには通常のBASEカート機能
(価格・在庫情報を含むog:price等)が備わっていることを確認した。つまり
このドメインは実際にはオンライン注文が可能な通常のBASEショップであり、
店舗説明にある「電話/FAX/メール注文のみ」は恐らく別の受付経路の案内
であって、オンラインストア自体は他のBASE店舗と同様にスクレイピング
可能と判断し、手動入力ではなく通常のスクレイパーとして実装する。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品構成について】
実データ確認済み: 全125件のうち、ブレンド6種(a〜F)・ストレート/産地別
11種(1〜8、うち1・3・4は浅煎り/中煎り/深煎りの2バリアントを別商品化)の
計17銘柄が対象。各銘柄は100g/250g/500gの3サイズと、それぞれに
「クリックポスト送料込み」という送料込み版(同一重量・別料金体系の
実質重複商品)が存在する。「クリックポスト送料込み」表記の商品は
NON_BEAN_KEYWORDSで除外し、残った銘柄×重量の中から商品名先頭に付く
重量表記をもとに最小重量(100g)を代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み: ドリップバッグ・水出し珈琲用バッグ・リキッドアイス
珈琲・コーノ/三洋産業製ペーパーフィルター・ネルドリッパー各種・
クッキー詰め合わせ・飲み比べセット各種(ストレート3種/ブレンド等)・
セイニチ ラミジップ(保存袋)・【定期便】(具体的な銘柄指定のない
サブスクリプション)が非対象。NON_BEAN_KEYWORDSで除外する。残り17件を
対象とする。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "珈琲もくれん",
    "url": "https://mokuren.official.ec/",
    "platform": "BASE",
    "address": "〒640-8125 和歌山県和歌山市島崎町3-27",
    "prefecture": "和歌山県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://mokuren.official.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ドリップバッグ", "水出し珈琲用バッグ", "リキッドアイス", "ドリッパー",
    "ペーパー", "クッキー", "飲み比べ", "３種", "ラミジップ", "定期便",
    "替布", "ポップンもっくん", "クリックポスト",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_mokuren.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_mokuren.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
