# -*- coding: utf-8 -*-
"""
scrape_matatabi.py

マタタビ珈琲豆店(matatabi.buyshop.jp、香川県高松市国分寺町国分486-3、
自家焙煎豆のオンライン販売)の商品情報を取得する。BASE系(buyshop.jp白ラベル
ドメイン)。

【プラットフォームについて】
候補リストでは実店舗サイト(matatabi-coffee.jp、カスタムHTML)が独自
tokutei.phpページを持つ通販店と想定されていたが、実データ確認の結果、
matatabi-coffee.jp自体には価格付きの商品一覧・カート機能が無く(お店紹介・
ブログのみ)、実際の通販はBASEの白ラベルドメイン「matatabi.buyshop.jp」
(matatabi-coffee.jp内のフッターリンク「thebase.in/to_app?...shop_id=
matatabi-buyshop-jp」から特定)で行われていることを確認した(2026-09時点)。
そのため本スクレイパーはmatatabi.buyshop.jpを対象とする。

【住所について】
実データ確認済み: matatabi.buyshop.jpの特定商取引法ページ(/law)では
「〒769-0102 香川県高松市国分寺町国分486-3」と表示される。候補リストの
「国分563-3」とは末尾の番地が異なるため、一次情報である特定商取引法
ページの住所を採用する。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量違いの重複について】
実データ確認済み(全69件): コロンビア・ケニア・タンザニア・ブラジル・
コスタリカ・グァテマラ・エチオピア(フレンチ・モカ)・マンデリン・
アメリカンブレンド・ショコラブレンド・ビターブレンド・カシスブレンド・
ブレンドNo.5の計13銘柄が100g/200g/500gの3サイズで個別商品登録されている。
商品名末尾の重量を除いた基準名でグルーピングし、最小重量(100g)を代表
として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み: ドリップバッグ単品(カシス/ショコラブレンド)・ギフト
ボックス入りドリップバッグ各種飲み比べセット・初めての方Web限定お試し
６種セット(アソート)・器具/雑貨(キーリング・キッチンタイマー・タンブラー・
フードクリップ・ランチトート・キャンバストート・カップ&ソーサー・
コーヒーカップ)が非対象。NON_BEAN_KEYWORDSで除外する。

【flavor_notes(2026-09-21追記)】
実データ確認済み: og:descriptionに商品ごとのテイスティング文が直接
入っている(対象14件全て確認、価格・スペック等の混入なし)。末尾に
焙煎度(「中深煎り」等)が地続きで付くが無関係なノイズではないため、
全文をそのまま採用する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "マタタビ珈琲豆店",
    "url": "https://matatabi.buyshop.jp/",
    "platform": "BASE",
    "address": "香川県高松市国分寺町国分486-3",
    "prefecture": "香川県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://matatabi.buyshop.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ドリップバッグ", "飲み比べセット", "お試し", "セット",
    "キーリング", "キッチンタイマー", "タンブラー", "フードクリップ",
    "トート", "カップ", "ソーサー", "グラス",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    flavor_notes = desc_el["content"].strip() if desc_el and desc_el.get("content") else None
    return {"title": title, "price": price, "flavor_notes": flavor_notes or None}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({
            "title": fields["title"], "price": fields["price"], "url": product_url,
            "flavor_notes": fields.get("flavor_notes"),
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_matatabi.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_matatabi.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
