# -*- coding: utf-8 -*-
"""
scrape_mywing.py

Coffee House MYWING(喫茶マイウイング、mywing.theshop.jp、〒087-0027
北海道根室市光和町1-23、自家焙煎豆のオンライン販売)の商品情報を取得
する。theShop(BASE系)。

robots.txt確認済み(2026-09時点): 他のtheShop/BASE系店舗(舟木コーヒー等)
と同一の記述("Generated by GRP")。python-requests/curl等は個別に
Disallow: /指定があるが、User-agent: *ルールでは実質許可。本スクレイパー
は識別可能な独自User-Agentを使用する。

住所は/lawページ(特定商取引法に基づく表記)にて実データ確認済み:
「〒087-0027 北海道根室市光和町1-23」(候補リストの住所と一致)。

【商品一覧の取得方法について】
実データ確認済み(2026-09時点、全16件): sitemap.xmlに列挙された/items/N
形式のURLを起点とする。

【非コーヒー豆商品の除外について】
実データ確認済み: ビスコッティ(焼き菓子)・MYWINGオリジナルドリップ
バッグ(1袋)・Coffee Gatorハンドドリッパー/直火式エスプレッソメーカー
(器具)が非対象。NON_BEAN_KEYWORDSで除外する。残り12件は全て単一銘柄
200gの焙煎豆(重量違いの重複なし)。

【flavor_notes(2026-09-21追記)】
実データ確認済み: og:descriptionにテイスティング文が直接入っており
(対象12件全て確認)、1件のみ末尾に「※開封後は密閉容器に保存し、
なるべく早めにお召し上がりください。」という店舗共通の保存方法注意書き
が続くため、これを除去する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "Coffee House MYWING(喫茶マイウイング)",
    "url": "https://mywing.theshop.jp/",
    "platform": "theShop(BASE系)",
    "address": "北海道根室市光和町1-23",
    "prefecture": "北海道",
    "robots_txt_status": "実質許可(2026-09確認。他のtheShop/BASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://mywing.theshop.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["ビスコッティ", "ドリップバッグ", "ハンドドリッパー", "エスプレッソメーカー", "Coffee Gator"]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
FLAVOR_STORAGE_NOTICE_PATTERN = re.compile(r"※開封後は密閉容器に保存し、なるべく早めにお召し上がりください。")


def extract_flavor_notes(description: str | None) -> str | None:
    """理由はモジュールdocstring参照。"""
    if not description:
        return None
    text = FLAVOR_STORAGE_NOTICE_PATTERN.sub("", description)
    return text.strip() or None


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    resp.encoding = "utf-8"
    return BeautifulSoup(resp.text, "html.parser")


def fetch_product_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    flavor_notes = extract_flavor_notes(desc_el["content"]) if desc_el and desc_el.get("content") else None
    return {"title": title, "price": price, "flavor_notes": flavor_notes}


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_product_urls()

    records = []
    flavored_records = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue

        detail = build_record({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "flavor_notes": fields.get("flavor_notes"),
        })
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_mywing.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_mywing.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
