# -*- coding: utf-8 -*-
"""
scrape_mamemaru.py

豆丸珈琲 鍛冶屋町焙煎所(mamemaru.official.ec、香川県高松市、自家焙煎豆の
オンライン販売)の商品情報を取得する。BASEの白ラベルドメイン「.official.ec」
(MARUTAKE COFFEE BEANSと同種)。

【住所について】
実データ確認済み(2026-09時点): 公式ストアの特定商取引法ページ
(https://mamemaru.official.ec/law)では「〒760-0029 香川県高松市丸亀町
7番地16-1208」と表示される。候補リストにあった「高松市鍛冶屋町4-1
フェスタ2ビル1F」(PR TIMESのプレスリリースに記載の実店舗所在地=生豆から
選べる注文焙煎所「鍛冶屋町焙煎所」の所在地)とは異なる。店舗の公開情報
(法人登記上の所在地または本店)と実店舗(焙煎所)の所在地が異なるケースと
考えられるため、一次情報である特定商取引法ページの住所を採用する。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量違いの重複について】
実データ確認済み(全186件): 「秋限定ブレンド〝秋いろ〟」のように同一銘柄が
100g/200g（100g単価の10%OFF）/300g（100g単価の15%OFF）/500g（100g単価の
20%OFF）の4サイズで個別商品登録されている。商品名末尾の重量表記および
「（100g単価のN%OFF）」という割引率注記を除いた基準名でグルーピングし、
最小重量(100g)を代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み(サンプル調査): 生豆(グリーンビーンズ)販売・器具・
ドリップバッグ単品・ギフトセット等はNON_BEAN_KEYWORDSで除外する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "豆丸珈琲 鍛冶屋町焙煎所",
    "url": "https://mamemaru.official.ec/",
    "platform": "BASE",
    "address": "香川県高松市丸亀町7番地16-1208",
    "prefecture": "香川県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://mamemaru.official.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "生豆", "グリーンビーンズ", "ドリップバッグ", "Drip Bag", "ギフト",
    "グッズ", "スプーン", "キャニスター", "福袋", "サブスク", "定期便",
    "コーヒーバッグ", "アイスコーヒー（リキッド）", "リキッド",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
DISCOUNT_NOTE_PATTERN = re.compile(r"[（(]\s*100g単価の\d+[%％]OFF\s*[）)]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def base_name_key(title: str) -> str:
    name = DISCOUNT_NOTE_PATTERN.sub("", title)
    name = WEIGHT_PATTERN.sub("", name)
    return re.sub(r"\s+", "", name).strip()


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base = base_name_key(item["title"])
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base)
        if existing is None:
            by_base_name[base] = item
        else:
            existing_weight_m = WEIGHT_PATTERN.search(existing["title"])
            existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
            if weight_key < existing_weight:
                by_base_name[base] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_mamemaru.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_mamemaru.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
