# -*- coding: utf-8 -*-
"""
scrape_mameyaito.py

自家焙煎まめ舎 伊藤珈琲(mameyaito.theshop.jp、宮城県仙台市泉区寺岡1-18-13、
自家焙煎豆のオンライン販売。販売責任者:伊藤正已)の商品情報を取得する。
THE SHOP(BASE系)。

【住所について】
公式サイトの特定商取引法ページ(https://mameyaito.theshop.jp/law)で実データ確認
(2026-09時点): 〒981-3204 宮城県仙台市泉区寺岡1-18-13。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by GRP")。
curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *ルールでは
実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品一覧・対象商品について】
実データ確認済み(2026-09時点、sitemap.xml): 全6件のうち4件が「季節のコーヒー豆
3種セット」「季節のコーヒー豆2種セット」「コーヒー豆3種ギフトセット」
「コーヒー豆2種ギフトセット」の複数銘柄詰め合わせセット(単一銘柄の焙煎豆で
はないため対象外)。実質的な単品の焙煎豆は「伊藤珈琲オリジナルブレンド」
(ブレンド)と「ディカフェコーヒー(カフェインレス)」(デカフェ)の2件のみ。

【重量について】
実データ確認済み: og:description中に「内容量：250g」という表記があるため、
そこから重量を抽出する(商品名自体には重量表記が無い)。

【flavor_notes(2026-09-22追記)】
実データ確認済み: og:descriptionに対象2件全てで簡潔なテイスティング文が
入っている。末尾に全件共通で「内容量：250gご注文日より3営業日以内に発送
いたします。●品質・鮮度を保つために...●送料について...」という重量/
発送/保存方法案内の定型文が続くため、この直前(既存の重量抽出に使う
「内容量：」マーカーの直前)で打ち切る。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "自家焙煎まめ舎 伊藤珈琲",
    "url": "https://mameyaito.theshop.jp/",
    "platform": "THE SHOP(BASE系)",
    "address": "宮城県仙台市泉区寺岡1-18-13",
    "prefecture": "宮城県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://mameyaito.theshop.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

# 理由はモジュールdocstring参照(複数銘柄の詰め合わせセットは単一銘柄の
# 焙煎豆商品ではないため対象外)
NON_BEAN_KEYWORDS = ["セット"]
WEIGHT_PATTERN = re.compile(r"内容量[：:]\s*(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    description = desc_el["content"] if desc_el and desc_el.get("content") else ""
    return {"title": title, "price": price, "description": description}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "non_bean": True,
            "product_url": item["url"],
        }

    parsed = parse_product(title)
    description = item.get("description") or ""
    weight_m = WEIGHT_PATTERN.search(description)
    flavor_notes = description[:weight_m.start()].strip() if weight_m else description.strip()
    flavor_notes = flavor_notes or None

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": flavor_notes,
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": int(weight_m.group(1)) if weight_m else None,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    non_bean_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record({**fields, "url": product_url})
        if detail is None:
            continue
        if detail.get("non_bean"):
            non_bean_records.append(detail)
        elif detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records, non_bean_records


if __name__ == "__main__":
    import json

    records, flavored_records, non_bean_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
        "non_bean_products_excluded": non_bean_records,
    }
    with open("data_mameyaito.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_mameyaito.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件、"
          f"非コーヒー豆{len(non_bean_records)}件は別枠に分離)")
