# -*- coding: utf-8 -*-
"""
scrape_alqahwa.py

自家焙煎珈琲 アル・カファ(Al Qahwa、www.al-qahwa.jpのオンライン販売、
愛知県岡崎市山綱町天神29-77、自家焙煎豆のオンライン販売)の商品情報を
取得する。BASE(独自ドメイン)。

【所在地について】
事前調査では「新城市」所在と伝えられていたが、実データ確認済み(2026-09、
www.al-qahwa.jp/law の特定商取引法に基づく表記ページ)では「愛知県岡崎市
山綱町天神29-77」が正式な事業者所在地として明記されていた。ドメインも
al-qahwa.jpは名前解決不可(存在しない)で、正しいドメインはwww.al-qahwa.jp
であることをDuckDuckGo検索経由で特定した。事業者住所を一次情報(法定表記
ページ)で裏取りできたため実装対象に含める(岡崎市は三河地方に含まれる)。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量について】
実データ確認済み(全14件): 商品バリエーションは「豆 200g」「粉 200g」(一部
商品は追加で「ドリップパック 8個」)の組み合わせで、豆・粉とも200gに固定。
商品名自体には重量表記が無いため、200gをこの店の固定重量として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み(全14件): ［特選紅茶］ダージリン/アールグレイ/アッサム/
セイロン(有機BIO)の4件は紅茶でコーヒー豆ではないため非対象。
NON_BEAN_KEYWORDSで除外する。残り10件(コーヒー豆)を対象とする。
"""

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "自家焙煎珈琲 アル・カファ",
    "url": "https://www.al-qahwa.jp/",
    "platform": "BASE",
    "address": "愛知県岡崎市山綱町天神29-77",
    "prefecture": "愛知県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://www.al-qahwa.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["特選紅茶", "紅茶"]
# 理由はモジュールdocstring参照(豆・粉とも200g固定、商品名に重量表記なし)
FIXED_WEIGHT_G = 200


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": FIXED_WEIGHT_G,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    item_urls = fetch_sitemap_urls()

    records = []
    flavored_records = []
    for item_url in item_urls:
        try:
            fields = extract_og_fields(fetch_page(item_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {item_url} ({e})")
            continue
        if not fields:
            continue
        detail = build_record({"title": fields["title"], "price": fields["price"], "url": item_url})
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_alqahwa.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_alqahwa.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
