# -*- coding: utf-8 -*-
"""
scrape_suilatte.py

自家焙煎珈琲すいらて(cafesuilatte.base.ec、〒650-0012 兵庫県神戸市中央区
北長狭通7-1-24、自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【非コーヒー豆商品の除外について】
実データ確認済み: 全92件のうち大半の単一農園銘柄・ブレンドにドリップ
パック版(15杯/10杯/5杯分等)が別商品として並列登録されている
(NON_BEAN_KEYWORDSの「ドリップパック」で除外)。その他、季節限定の
「秋の夜長珈琲」(2種の焙煎豆詰め合わせ・ドリップパック・送料無料
セットで単一銘柄ではない)・各種【ギフト】(はじめてのすいらてセット、
コーヒーとおやつの時間、コーヒーで世界を旅しよう、やさしいカフェイン
レスの旅、神戸BOX、おまかせ、BOX(S/M/ML/L)中身別売り、いずれも複数
銘柄の詰め合わせまたは空箱)・Coffee & Cookie Gift Bag・すいらてのクッキー
(菓子)・リネンフィルター２枚セット/コーヒースターターキット(器具)・
コットンバッグ/メッセージカード(雑貨)が非対象。NON_BEAN_KEYWORDSで
除外する。残り33件(定番ブレンド4種+デカフェ4種を含む単一農園等29種)を
対象とする。

【flavor_notes/farm_note(テイスティングノート・農園情報)について
(2026-09-20追記)】
実データ確認済み(30商品サンプル調査): 他のBASE系店舗と共通のテーマの
p[class*="item-detail_description"]要素に、「【焙煎度合い】」「【農園】」
「【地域】」「【品種】」「【精製】」「【標高】」ラベルの構造化情報に続けて
「味わいについて」見出し以降に店主による風味紹介文、その後「農園・精製
について」見出し以降に農園の背景説明が続く一貫した構造だったが、この
要素自体を一切読んでいなかった。「味わいについて」〜「農園・精製に
ついて」間の自由文をflavor_notesとして採用し、「農園」「地域」「品種」
「精製」「標高」ラベルはfarm_note用フィールドに反映する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status, normalize_processing_method

SHOP_INFO = {
    "name": "自家焙煎珈琲すいらて",
    "url": "https://cafesuilatte.base.ec/",
    "platform": "BASE",
    "address": "兵庫県神戸市中央区北長狭通7-1-24",
    "prefecture": "兵庫県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://cafesuilatte.base.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ドリップパック", "秋の夜長珈琲", "ギフト", "クッキー", "Cookie",
    "リネンフィルター", "コーヒースターターキット", "コットンバッグ", "メッセージカード",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
# 実データ確認済み: ラベル行は「【農園】値」(括弧・コロン無し)と
# 「農園：値」(コロン区切り・括弧無し)の2形式が混在する
FARM_LABEL_NAMES = "焙煎度合い|農園|地域|品種|精製|製法|標高|認証"
BRACKET_LABEL_PATTERN = re.compile(rf"^【({FARM_LABEL_NAMES})】\s*(.*)$")
BARE_LABEL_PATTERN = re.compile(rf"^({FARM_LABEL_NAMES})[：:]\s*(.*)$")
ANY_BRACKET_PATTERN = re.compile(r"^【[^】]+】")
FARM_LABEL_TO_FIELD = {
    "農園": "farm_name",
    "地域": "region_detail",
    "品種": "variety_note",
    "標高": "altitude_note",
}
# 理由はモジュールdocstring参照: ラベルブロックの直後に「味わいについて」
# という見出しが挟まる商品と、見出し無しで直接本文が始まる商品が混在する
FLAVOR_HEADING = "味わいについて"
FLAVOR_STOP_HEADINGS = {
    "農園について", "農園・精製について", "飲み方のおすすめ",
    "ホットで楽しむ場合", "アイスコーヒーで楽しむ場合", "フードペアリング",
}


def parse_flavor_and_farm(soup: BeautifulSoup) -> tuple[str | None, dict, str | None]:
    """理由はモジュールdocstring参照。"""
    el = soup.select_one('p[class*="item-detail_description"]')
    if not el:
        return None, {}, None
    farm: dict = {}
    processing_raw = None
    flavor_lines = []
    mode = "label"
    for raw_line in el.get_text(separator="\n").split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        if line == FLAVOR_HEADING:
            # 見出し自体はどのタイミングで出現しても本文に含めない
            if mode == "label":
                mode = "flavor"
            continue
        if mode == "label":
            m = BRACKET_LABEL_PATTERN.match(line) or BARE_LABEL_PATTERN.match(line)
            if m:
                label, value = m.group(1).strip(), m.group(2).strip()
                if label in FARM_LABEL_TO_FIELD and value:
                    farm[FARM_LABEL_TO_FIELD[label]] = value
                elif label in ("精製", "製法") and value:
                    processing_raw = value
                continue
            if line.startswith("※"):
                # ラベルブロック内の補足注記(例:デカフェ処理の説明)は無視して
                # ラベルブロックの継続として扱う(本文開始とはみなさない)
                continue
            # ラベル形式に一致しない行に到達したらラベルブロック終了
            mode = "flavor"
        if mode == "flavor":
            if line in FLAVOR_STOP_HEADINGS or line.startswith("※") or ANY_BRACKET_PATTERN.match(line):
                mode = "done"
                continue
            flavor_lines.append(line)
    flavor_notes = "".join(flavor_lines) or None
    return flavor_notes, farm, processing_raw


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"] or normalize_processing_method(item.get("processing_method_raw")),
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "farm_name": item.get("farm", {}).get("farm_name"),
        "region_detail": item.get("farm", {}).get("region_detail"),
        "altitude_note": item.get("farm", {}).get("altitude_note"),
        "variety_note": item.get("farm", {}).get("variety_note"),
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            soup = fetch_page(product_url)
            fields = extract_og_fields(soup)
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        flavor_notes, farm, processing_raw = parse_flavor_and_farm(soup)
        all_items.append({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "flavor_notes": flavor_notes,
            "farm": farm,
            "processing_method_raw": processing_raw,
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_suilatte.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_suilatte.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
