# -*- coding: utf-8 -*-
"""
scrape_emame.py

ザ・コーヒービーンズ(emame.theshop.jp、徳島県鳴門市撫養町林崎字北殿町
57-1、自家焙煎豆のオンライン販売)の商品情報を取得する。BASE系(theShop
白ラベルドメイン)。

【住所について】
実データ確認済み(2026-09時点): 公式ストアの特定商取引法ページ
(https://emame.theshop.jp/law)で「〒772-0016 徳島県鳴門市撫養町林崎字
北殿町57-1」と一致確認済み。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量違いの重複について】
実データ確認済み(全80件): 「[11] パッセイオ農園＊ブラジル」のように番号
付きの銘柄が100g/250gの2サイズで個別商品登録されている。商品名末尾の
重量を除いた基準名でグルーピングし、最小重量(100g)を代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み(サンプル調査): 器具(紙フィルターを使わないコーヒーポット
等)・ドリップバッグ・ギフトセットが非対象と想定されるため
NON_BEAN_KEYWORDSで除外する。

【flavor_notes(テイスティングノート)について(2026-09-20追記)】
実データ確認済み(サンプル調査): 他のBASE系店舗と同じ共通テーマの
p[class*="item-detail_description"]要素に、簡潔で具体的な風味描写がある
(例:「ビター、ココアの風味があります。スムーズで厚みのある味わいです。」)。
以前はog:title/価格のみ取得し、この要素自体を一切読んでいなかった。
GONZO CAFE&BEANS等と同様、末尾に「※」で始まる注記が付く可能性がある
ためその手前までを採用する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "ザ・コーヒービーンズ",
    "url": "https://emame.theshop.jp/",
    "platform": "BASE",
    "address": "徳島県鳴門市撫養町林崎字北殿町57-1",
    "prefecture": "徳島県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://emame.theshop.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ポット", "ドリップバッグ", "ギフト", "フィルター", "グッズ", "セット",
]
NUMBER_PREFIX_PATTERN = re.compile(r"^\[\d+\]\s*")
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
FLAVOR_STOP_PATTERN = re.compile(r"^※")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def parse_flavor_notes(soup: BeautifulSoup) -> str | None:
    """理由はモジュールdocstring参照。"""
    el = soup.select_one('p[class*="item-detail_description"]')
    if not el:
        return None
    lines = []
    for raw_line in el.get_text(separator="\n").split("\n"):
        line = raw_line.strip()
        if not line:
            continue
        if FLAVOR_STOP_PATTERN.match(line):
            break
        lines.append(line)
    return "".join(lines) or None


def base_name_key(title: str) -> str:
    name = WEIGHT_PATTERN.sub("", title)
    return re.sub(r"\s+", "", name).strip()


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = base_name_key(item["title"])
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parse_target = NUMBER_PREFIX_PATTERN.sub("", title)
    parsed = parse_product(parse_target)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "flavor_notes": item.get("flavor_notes"),
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            soup = fetch_page(product_url)
            fields = extract_og_fields(soup)
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "flavor_notes": parse_flavor_notes(soup),
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_emame.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_emame.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
