# -*- coding: utf-8 -*-
"""
scrape_trunkcoffee.py

TRUNK COFFEE(trunkcoffee.thebase.in、愛知県名古屋市東区泉2-28-24
東和高岳ビル1F、自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品の大半が非コーヒー豆商品であることについて】
実データ確認済み: sitemap.xmlに含まれる全93商品のうち、実際の焙煎豆単品は
22件のみで、残り71件はORIGAMI/HARIO/Kalita製のドリッパー・ペーパー
フィルター・カッピング器具、オリジナルマグ・グラス・タンブラー、
Tシャツ・ポロシャツ等のアパレル、ドリップバッグ詰め合わせギフト、
西尾産オーガニック抹茶(コーヒー豆ではない)、インスタントコーヒー
スティック等の物販・グッズである(TRUNK COFFEEは自家焙煎豆に加えて
自社ブランドの器具・グッズ販売も手広く行っている店舗のため)。

キーワードのブラックリスト方式では網羅しきれない(グッズの種類が
非常に多い)ため、代わりに実データで確認した「焙煎豆単品の商品名は
必ず先頭が重量表記(例: 100g,・500g,)で始まる」という命名規則を逆手に
取り、ブラケット付き接頭辞(【再入荷！】【数量限定/ 希少】等)と絵文字
(❤️⚡️等)を除去した後に先頭が半角数字+g/ｇで始まるものだけを焙煎豆
候補として採用するホワイトリスト方式を採用する。この方式で全22件の
焙煎豆単品を過不足なく検出できることを実データで確認済み。

【重量バリエーションについて】
実データ確認済み: 主要8銘柄が100g/250g/500gの3サイズ(パナマ ゲイシャ・
レリダのみ数量限定で50g単一)で個別商品登録されている。商品名から
ブラケット接頭辞・重量・絵文字/記号類を除いた基準名でグルーピングし、
最小重量を代表として採用する。

【在庫状況について】
実データ確認済み: BASE商品ページの初期HTMLはJS描画前のためページ内に
実際の在庫有無を示す構造化データが無い(「SOLD OUT」という文字列は
在庫の有無に関わらず全ページのJSバンドル内テンプレート文字列として
常に1回出現するため使用不可)。亀山珈琲焙煎所・珈琲豆山倉と同様、
商品名のテキストパターンのみでdetect_stock_statusに判定させる。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "TRUNK COFFEE",
    "url": "https://trunkcoffee.thebase.in/",
    "platform": "BASE",
    "address": "愛知県名古屋市東区泉2-28-24 東和高岳ビル1F",
    "prefecture": "愛知県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://trunkcoffee.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

BRACKET_TAG_PATTERN = re.compile(r"【[^】]*】")
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")
# 焙煎豆単品候補判定: ブラケット接頭辞と先頭の絵文字/記号/空白を除去した後、
# 先頭が半角/全角数字+g/ｇで始まるものだけを対象とする(上記docstring参照)。
LEADING_NOISE_PATTERN = re.compile(r"^\W+")
BEAN_START_PATTERN = re.compile(r"^\d+\s*[gｇ]")
# グルーピング用キー正規化: 単語・かな・カナ・漢字・長音符以外(絵文字・記号・
# 空白・カンマ・スラッシュ・引用符等)をすべて除去し、重量違い/表記ゆれの
# 影響を受けない基準名を作る。
KEY_NOISE_PATTERN = re.compile(r"[^\w一-龠ぁ-んァ-ヶー]+")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()

    is_bean = bool(BEAN_START_PATTERN.match(LEADING_NOISE_PATTERN.sub("", BRACKET_TAG_PATTERN.sub("", title))))
    if not is_bean:
        return None

    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def build_group_key(title: str) -> str:
    key = BRACKET_TAG_PATTERN.sub("", title)
    key = WEIGHT_PATTERN.sub("", key)
    key = KEY_NOISE_PATTERN.sub("", key)
    return key.lower()


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = build_group_key(item["title"])
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = BRACKET_TAG_PATTERN.sub("", item["title"]).strip()
    title = re.sub(r"\s+", " ", title)
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_trunkcoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_trunkcoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
