# -*- coding: utf-8 -*-
"""
scrape_kobitocoffee.py

姫路 総社本町珈琲店(kobitocoffee.base.shop、兵庫県姫路市総社本町159番地、
自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

【住所について】
候補リストでは市区町村までの記載(姫路市)だったが、公式サイトの特定商
取引法ページ(https://kobitocoffee.base.shop/law)で確認したところ
「〒670-0015 兵庫県姫路市総社本町159番地」(事業者名: 木村のはら)である
ことを確認したため、こちらを正としている。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【非コーヒー豆商品の除外について】
実データ確認済み: sitemap.xml記載の全19件のうち、オリジナルドリップバッグ
(器具・加工品)・２周年記念グッズ(手のひらまぐかっぷ・オリジナル保冷保温
バッグ、器具)・こーひーてん おりじなるきゃにすたー(器具)・
「M様専用」「S様専用」「Mさま専用便」等の特定顧客向け専用注文(4件)・
「500g珈琲豆セット」(実データ確認: グァテマラSHB 300g+ブラジル・サントス
200gの特定客向け詰め合わせで通常カタログ商品ではない)・
「モカ イルガチェフG1➕総社ブレンド」(2銘柄詰め合わせ)が非対象。
NON_BEAN_KEYWORDSで除外する。残り7件(総社ブレンド・ブラジル・サントス・
コロンビア スプレモ・アイスコーヒーブレンド・キリマンジャロ タンザニア
AA・モカ イルガチェフG1ナチュラル・マンデリン スペシャルG1、いずれも
100g×2=200g)を対象とする。

【重量表記について】
実データ確認済み: 商品名が「100g×2=200ｇ」のように内訳と合計の2つの
重量を含む場合があるため、タイトル中の最後に出現する重量(=合計重量)を
採用する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "姫路 総社本町珈琲店",
    "url": "https://kobitocoffee.base.shop/",
    "platform": "BASE",
    "address": "兵庫県姫路市総社本町159番地",
    "prefecture": "兵庫県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://kobitocoffee.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ドリップバッグ", "記念グッズ", "まぐかっぷ", "保冷保温バッグ",
    "きゃにすたー", "専用", "セット", "➕", "ギフト",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_matches = WEIGHT_PATTERN.findall(title)
    weight_g = int(weight_matches[-1]) if weight_matches else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    records = []
    flavored_records = []
    for item in all_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_kobitocoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_kobitocoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
