# -*- coding: utf-8 -*-
"""
scrape_circuscoffee.py

サーカスコーヒー(shop.circus-coffee.jp、京都府京都市北区紫竹下緑町32、
自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量違いの重複について】
実データ確認済み: 全113件中、主力の22銘柄が100g/200g/500gの最大3サイズ
(銘柄によっては一部サイズのみ)で個別商品登録されている。商品名末尾の
【N g】表記を除いた基準名でグルーピングし、最小重量を代表として採用する。
なお「パプアニューギニア　Mt.ハーゲン・シンバイ地域」と「パプアニュー
ギニア・ハセン農園　〜修道院と共に〜天空の森」は産地表記が似ているが
別農園の別銘柄(実データ確認済み、説明文で別農園と明記)であるため、
別商品として扱う。

【非コーヒー豆商品の除外について】
実データ確認済み: 全113件のうち、以下が非対象。
- 周年記念の限定缶ギフト(中身の豆を選択式にしており単一銘柄を特定できない)
- 定番ブレンド４種類セット・２種のおすすめコーヒーセット(お試し用の
  複数銘柄アソート、単一銘柄を特定できない)
- コーヒー缶ギフト・ドリップカフェギフト各種(ギフト箱・ドリップバッグ)
- カフェオレベース/アイスコーヒーベース各種(液体ベース、豆ではない)
- 手挽きミルスターターセット(コーヒーミル本体とのセット商品)
- 紙袋・ポチ袋レターセット・折り紙(コーヒー豆と無関係な雑貨)
- 珈琲と文化No.137/138(冊子)・北に上ル(冊子と見られる)
- ボトル＋コーヒー豆のセット商品(ボトル込みのため豆単体と価格が対応しない)
- 「まいにち１杯便」「たっぷり２杯便」等のサブスクリプション定期便
  (月額表記で特定の銘柄・重量に対応しない)
- 水出しアイスコーヒーパック(液体不使用のパックだが単一銘柄の豆売りでは
  ないため他店と同様の方針で除外)
- オリジナルminiトートバッグ＆ドリップバッグセット(雑貨+ドリップバッグ)
- アバカ(プラス)コーヒーフィルター各種(器具)
NON_BEAN_KEYWORDSで除外する。残り22銘柄(ブレンド8種+ストレート/産地
指定14種)を対象とする。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "サーカスコーヒー",
    "url": "https://circus-coffee.jp/",
    "platform": "BASE",
    "address": "京都府京都市北区紫竹下緑町32",
    "prefecture": "京都府",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://shop.circus-coffee.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "周年限定缶", "４種類セット", "缶ギフト", "ドリップカフェ", "カフェオレベース",
    "ミルスターターセット", "おすすめコーヒーセット", "紙袋", "ポチ袋", "折り紙",
    "珈琲と文化", "北に上ル", "ボトル＋コーヒー豆", "杯便", "水出しアイスコーヒーパック",
    "トートバック", "コーヒーフィルター",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_circuscoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_circuscoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
