# -*- coding: utf-8 -*-
"""
scrape_taiyocoffee.py

大洋珈琲(taiyocoffee.com、大阪市中央区内久宝寺町3-3-15、自家焙煎豆の
オンライン販売)の
商品情報を取得する。公式サイト(www.taiyocoffee.com)自体はWordPress製の
案内サイトで、実際の通販は別ドメインのBASEショップ(taiyocoffee.base.shop)
で運営されている。BASE。

robots.txt確認済み(2026-09時点): taiyocoffee.base.shopは他のBASE系店舗と
同一の記述("Generated by GRP")。curl/python-requests等は個別にDisallow: /
指定があるが、User-agent: *ルールでは実質許可。本スクレイパーは識別可能な
独自User-Agentを使用する。

【重量違いの重複について】
実データ確認済み: 全商品中、大半のブレンド・ストレート銘柄が100g/200g/500g
の3サイズ(一部200g/500gのみ、ブルーマウンテン系は100g/200g/500gの3サイズ)
で個別商品登録されている。末尾の重量表記を除いた基準名でグルーピングし、
最小重量を代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み: ギフト各種(コーヒー詰め合わせBOX、ドリップパック箱入り、
ギフト箱)・セイロン紅茶・オリジナルリキッドアイスコーヒー(瓶入り液体)・
お手軽!水出しアイスコーヒー(液体パック)・ドリップパック各種(個包装)・
オーダー焙煎シリーズ(重量表記がなく、通常ラインナップと重複する特別
注文枠のため識別不能)・500g10個お徳用(業務用一括まとめ買い、通常の
100g/200g/500gラインナップと別枠の卸売的商品)が非対象。
NON_BEAN_KEYWORDSで除外する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "大洋珈琲",
    "url": "https://www.taiyocoffee.com/",
    "platform": "BASE",
    "address": "大阪府大阪市中央区内久宝寺町3-3-15",
    "prefecture": "大阪府",
    "robots_txt_status": "実質許可(2026-09確認。taiyocoffee.base.shopは他のBASE系店舗と"
                          "同一の記述。curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://taiyocoffee.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ギフト", "紅茶", "リキッドアイスコーヒー", "水出しアイスコーヒー",
    "ドリップパック", "オーダー焙煎", "お徳用",
]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        prev = previous.get(item["url"])
        if is_unchanged(prev, raw_name=item["title"]):
            records.append(prev)
            continue
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_taiyocoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_taiyocoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
