# -*- coding: utf-8 -*-
"""
scrape_coffeekazoku.py

珈琲家族(coffee-kazoku.com、coffeekazoku.thebase.inのオンライン販売、
愛知県碧南市松本町97、自家焙煎豆のオンライン販売)の商品情報を取得する。
BASE。

【本店ドメインについて】
実データ確認済み(2026-09時点): coffee-kazoku.com はSNI/証明書エラーで
到達不能(さくらのレンタルサーバーの初期ページが表示されるケースもあり、
実質的に運用されていないと判断)。実際の通販はcoffeekazoku.thebase.in
(BASE、og:title「珈琲家族ONLINE SHOP powered by BASE」)で行われている
ことを確認済みのため、こちらをBASE_URLとして使用する。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量について】
実データ確認済み: 対象商品(【珈琲豆】プレフィックス付き21件)は商品名に
重量表記が無く、各商品の説明文(og:description)に共通して「※100g単位の
値段になります」という注記があることを確認済み(複数商品でサンプル確認)。
重量バリエーションのセレクトボックスも無いため、100gをこの店の固定重量
として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み(全33件): 珈琲家族カフェ・オ・レ・ベース(液体)・
ブラックティー(加糖)・【無糖】/【加糖】リキッドアイスコーヒー(液体)・
マドラー式/ドリップ式コーヒーバック(ドリップバッグ)・マドラー式＆
ドリップ式バックギフト・レギュラーコーヒー３種ギフト・【送料お得！
３種セット】マイルド/苦味/酸味好き/飲み比べセット(いずれも複数銘柄の
詰め合わせで単一銘柄を特定できない)が非対象。NON_BEAN_KEYWORDSで除外
する。残り21件(【珈琲豆】プレフィックス付き、MIXブレンド含む)を対象と
する。
"""

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "珈琲家族",
    "url": "https://coffeekazoku.thebase.in/",
    "platform": "BASE",
    "address": "愛知県碧南市松本町97",
    "prefecture": "愛知県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://coffeekazoku.thebase.in"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["カフェ・オ・レ・ベース", "ブラックティー", "リキッドアイスコーヒー", "コーヒーバック", "ギフト", "セット"]
# 理由はモジュールdocstring参照(重量バリエーションが無く全商品共通で100g単位)
FIXED_WEIGHT_G = 100


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": FIXED_WEIGHT_G,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    item_urls = fetch_sitemap_urls()

    records = []
    flavored_records = []
    for item_url in item_urls:
        try:
            fields = extract_og_fields(fetch_page(item_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {item_url} ({e})")
            continue
        if not fields:
            continue
        detail = build_record({"title": fields["title"], "price": fields["price"], "url": item_url})
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_coffeekazoku.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_coffeekazoku.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
