# -*- coding: utf-8 -*-
"""
scrape_coffeeroastkobe.py

コーヒーロースト神戸六甲道(coffeeroastkobe.com、〒657-0036 神戸市灘区桜口町
５丁目１−１ウェルブ六甲道５番街１番館１階、自家焙煎豆のオンライン販売)の
商品情報を取得する。BASE。

【プラットフォーム識別について】
実データ確認済み: 運営会社サイト本体(coffeeroastkobe.com)はWordPress製で、
ヘッダー/フッターに旧ドメイン「coffeeroast65.bitter.jp」へのリンクがあるが、
bitter.jpドメイン自体は本体サイトへの導線が置かれているだけの空ページで、
実際の購入導線(ヘッダーの「onlineshop」アイコン、/beans/ページの各産地
リンク)は全て https://roastkobe.base.shop/items/... (BASE)を指している。
roastkobe.base.shop の robots.txt は他のBASE系店舗と同一の記述("Generated
by GRP")であることを確認済み。よって実質的な販売プラットフォームはBASEと
判断し、BASE_URLをroastkobe.base.shopとする。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品一覧の取得方法について】
実データ確認済み: sitemap.xml(6件の/items/付きURL)を商品一覧の取得元とする。
小規模店舗で全6件が該当。

【非コーヒー豆商品の除外について】
実データ確認済み: 全6件のうち「WORLD　MIX set」(og:description「その時期の
各国のオススメ3~4種類入ったセット」明記の複数銘柄詰め合わせで単一銘柄では
ない)が非対象。NON_BEAN_KEYWORDSで除外する。残り5件(JAMAICA/HAWAII/PANAMA
のシングルオリジン3種+BITTER set/MILDSETの独自ブレンド2種)を対象とする。
「BITTER set」「MILDSET」はog:descriptionが「苦いコーヒーが好みの方に」
「酸味にも苦味にも片寄ってなく...バランス良いセット」という単一の焙煎豆の
風味説明であり、詰め合わせを示す記載が無いため単一ブレンド銘柄として扱う。

【在庫状況について】
実データ確認済み: 商品詳細ページのHTML内、価格表示の直後に
`<p class="item-detail_soldOut_XXXXXXXX">SOLD OUT</p>`という構造化要素が
あり、確認時点では全6件がSOLD OUT状態だった。og:title/og:descriptionの
メタタグだけでは分からない情報のため、詳細ページ本文をclass名に"soldOut"を
含む要素の有無で判定し、structural_out_of_stockとして渡す。ルールに従い
欠品商品も削除せずout_of_stockフラグ付きで結果に含める。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "コーヒーロースト神戸六甲道",
    "url": "https://roastkobe.base.shop/",
    "platform": "BASE",
    "address": "兵庫県神戸市灘区桜口町5丁目1-1 ウェルブ六甲道5番街1番館1階",
    "prefecture": "兵庫県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://roastkobe.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["MIX set"]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    soldout_el = soup.select_one('[class*="soldOut"]')
    structural_out_of_stock = bool(soldout_el and "SOLD OUT" in soldout_el.get_text())
    return {"title": title, "price": price, "structural_out_of_stock": structural_out_of_stock}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", item["title"]).strip()
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        existing = by_base_name.get(base_name)
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"]) if existing else None
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        if existing is None or weight_key < existing_weight:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = item["title"].strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title, item["structural_out_of_stock"])
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({
            "title": fields["title"],
            "price": fields["price"],
            "url": product_url,
            "structural_out_of_stock": fields["structural_out_of_stock"],
        })

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_coffeeroastkobe.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_coffeeroastkobe.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
