# -*- coding: utf-8 -*-
"""
scrape_kazekumomame.py

風雲Coffeeroastery & Books(kazekumomame.base.shop、長野県伊那市高遠町
〈信州高遠〉、自家焙煎豆のオンライン販売)の商品情報を取得する。BASE。

住所について: BASEの特定商取引法ページが運営者住所を非公開設定にして
おり(BASE株式会社の代理住所のみ表示)、番地までは一次情報で確認できて
いない。ただし公式サイト本文に「信州高遠にある小さいけれどこだわりの
コーヒー豆焙煎工房です」との明記があり、「高遠」は長野県伊那市高遠町を
指す一意性の高い地名(他県に同名の紛らわしい地名なし)のため、市区町村
レベルの所在地としては確度が高いと判断した。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【豆/粉表記・重量違いの重複について】
実データ確認済み: 同一銘柄が【豆】【粉】の挽き方違い、および100g/200gの
重量違いで個別商品登録されている。商品名先頭の「【豆】」「【粉】」を
除いた基準名でグルーピングし、【豆】を優先(【粉】しか無い場合は【粉】を
採用)した上で最小重量を代表として採用する。

【非コーヒー豆商品の除外について】
実データ確認済み: 全13件のうち「自家焙煎コーヒー豆オススメ３種」(浅煎り・
中煎り・深煎りの3種詰め合わせ、豆/粉×300g/600gの4パターン)・ドリップ
パック12g×5袋セットが非対象。NON_BEAN_KEYWORDSで除外する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "風雲Coffeeroastery",
    "url": "https://kazekumomame.base.shop/",
    "platform": "BASE",
    "address": "長野県伊那市高遠町",
    "prefecture": "長野県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://kazekumomame.base.shop"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["オススメ３種", "ドリップパック"]
GRIND_PREFIX_PATTERN = re.compile(r"^【(豆|粉)】")
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def pick_canonical_items(items: list[dict]) -> list[dict]:
    by_base_name: dict[str, dict] = {}
    for item in items:
        base_name = WEIGHT_PATTERN.sub("", GRIND_PREFIX_PATTERN.sub("", item["title"])).strip()
        is_whole_bean = item["title"].startswith("【豆】") or "【豆】" not in item["title"] and "【粉】" not in item["title"]
        weight_m = WEIGHT_PATTERN.search(item["title"])
        weight_key = int(weight_m.group(1)) if weight_m else float("inf")
        rank = (0 if is_whole_bean else 1, weight_key)

        existing = by_base_name.get(base_name)
        if existing is None:
            by_base_name[base_name] = item
            continue
        existing_is_whole_bean = (
            existing["title"].startswith("【豆】")
            or ("【豆】" not in existing["title"] and "【粉】" not in existing["title"])
        )
        existing_weight_m = WEIGHT_PATTERN.search(existing["title"])
        existing_weight = int(existing_weight_m.group(1)) if existing_weight_m else float("inf")
        existing_rank = (0 if existing_is_whole_bean else 1, existing_weight)
        if rank < existing_rank:
            by_base_name[base_name] = item
    return list(by_base_name.values())


def build_record(item: dict) -> dict | None:
    title = GRIND_PREFIX_PATTERN.sub("", item["title"]).strip()
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()

    all_items = []
    for product_url in product_urls:
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        all_items.append({"title": fields["title"], "price": fields["price"], "url": product_url})

    canonical_items = pick_canonical_items(all_items)

    records = []
    flavored_records = []
    for item in canonical_items:
        detail = build_record(item)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_kazekumomame.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_kazekumomame.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
