# -*- coding: utf-8 -*-
"""
scrape_slothcoffee.py

喫茶スロース(slothcoffee.jp、slothcoffee.base.ecのオンライン販売、愛知県
蒲郡市神明町９番１４号 市川ビル１F、自家焙煎豆のオンライン販売)の商品情報を
取得する。BASE。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【重量について】
実データ確認済み: 対象となるコーヒー豆商品は全て商品名末尾に「200g」を
明記しており(kamecoffee等と同じ、重量帯を商品バリエーションで持たせる
soh-coffeeとは異なるパターン)、通常のBASEテンプレート(meta抽出+商品名の
WEIGHT_PATTERN)で問題なく取得できる。

【非コーヒー豆商品の除外について】
実データ確認済み(全33件): 喫茶スロースTシャツ各色(大橋裕之さんデザイン・
台湾レトロ風、計9件)・ギフト用ドリップバッグ各種・マイルド/ビター
ブレンドのコーヒードリップパック家庭用・ドリップバッグバラエティセット・
メキシコデカフェドリップバッグ(個別包装・10個入り)・水出しアイスコーヒー
パック・松屋式金枠ドリッパー・ハリオV60用ペーパーフィルター各種が非対象。
NON_BEAN_KEYWORDSで除外する。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status

SHOP_INFO = {
    "name": "喫茶スロース",
    "url": "https://slothcoffee.jp/",
    "platform": "BASE",
    "address": "愛知県蒲郡市神明町９番１４号 市川ビル１F",
    "prefecture": "愛知県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://slothcoffee.base.ec"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["Tシャツ", "ドリップ", "水出しアイスコーヒーパック", "ドリッパー", "ペーパーフィルター"]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    item_urls = fetch_sitemap_urls()

    records = []
    flavored_records = []
    for item_url in item_urls:
        try:
            fields = extract_og_fields(fetch_page(item_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {item_url} ({e})")
            continue
        if not fields:
            continue
        detail = build_record({"title": fields["title"], "price": fields["price"], "url": item_url})
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_slothcoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_slothcoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
