# -*- coding: utf-8 -*-
"""
scrape_chibacoffee.py

チバコーヒー(base.chibacoffee.jp、栃木県宇都宮市陽東3-8-4ほか、自家焙煎豆の
オンライン販売)の商品情報を取得する。BASE(カスタムドメイン)。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品情報の取得方法について】
実データ確認済み: 他のBASE系店舗と同様、OGPメタタグ(`og:title`・
`product:price:amount`)から商品名・価格を取得する。

【非コーヒー豆商品の除外について】
実データ確認済み: 全34件のうちドリップバッグ(浅煎〜極深煎の5種)・ペーパー
フィルター(CAFECおよび「おいしい珈琲屋の」ブランドのフィルター類)・
スマートドリップフィルター・ギフトボックス各種・クラフト手提げ袋が非対象。
NON_BEAN_KEYWORDSで除外する。重量表記(g)は商品名に無く、単一サイズ販売
(1袋)のため重量重複の処理は不要。

【flavor_notes(2026-09-21追記)】
実データ確認済み: og:descriptionは「100gテイスティング文産地：…／規格：
…／品種：…／精選：…／焙煎：…」のように、先頭の重量表記の直後にテイス
ティング文、その後にスペック情報が区切り文字無しで連続する構成だった
(対象18件全てで確認)。先頭の重量表記を除去した上で、スペックラベル
(産地/規格/品種/精選/焙煎/脱カフェイン方法/「ベース（」)のうち最初に
出現するものの直前までを採用する。デカフェ豆1件は配合比率とスペックの
みでテイスティング文が存在せず、genuineな欠落と確認した。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "チバコーヒー",
    "url": "https://chibacoffee.jp/",
    "platform": "BASE",
    "address": "栃木県宇都宮市陽東3-8-4",
    "prefecture": "栃木県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://base.chibacoffee.jp"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = [
    "ドリップバッグ", "フィルター", "ギフトボックス", "手提げ袋",
]
WEIGHT_PREFIX_PATTERN = re.compile(r"^\s*\d+\s*[gｇ]")
FLAVOR_STOP_PATTERN = re.compile(
    r"産地[：:]|品種[：:]|規格[：:]|精選[：:]|焙煎[：:]|脱カフェイン方法[：:]|ベース（"
)
CONTROL_CHAR_PATTERN = re.compile(r"[\x00-\x1f]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_flavor_notes(description: str | None) -> str | None:
    """理由はモジュールdocstring参照。"""
    if not description:
        return None
    text = WEIGHT_PREFIX_PATTERN.sub("", description)
    m = FLAVOR_STOP_PATTERN.search(text)
    text = text[:m.start()] if m else text
    text = CONTROL_CHAR_PATTERN.sub("", text).strip()
    return text or None


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    title_el = soup.select_one('meta[property="og:title"]')
    if not title_el or not title_el.get("content"):
        return None
    title = title_el["content"].split(" | ")[0].strip()
    if any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    desc_el = soup.select_one('meta[property="og:description"]')
    description = desc_el["content"] if desc_el and desc_el.get("content") else None
    return {"title": title, "price": price, "flavor_notes": extract_flavor_notes(description)}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(item: dict) -> dict | None:
    title = item["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": item["price"],
            "product_url": item["url"],
        }

    stock_status = detect_stock_status(title)

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "flavor_notes": item.get("flavor_notes"),
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": item["price"],
        "weight_g": None,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": item["url"],
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    product_urls = fetch_sitemap_urls()
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record({
            "title": fields["title"], "price": fields["price"],
            "flavor_notes": fields.get("flavor_notes"), "url": product_url,
        })
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_chibacoffee.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_chibacoffee.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
