# -*- coding: utf-8 -*-
"""
scrape_igamameichi.py

豆一珈琲(www.mameichi.net、三重県伊賀市阿保718-3、自家焙煎スペシャルティ
コーヒーのオンライン販売、木金土日のみ営業)の商品情報を取得する。
カスタムドメインでBASEを利用(独自ドメインがBASEにプロキシされている)。

【ファイル名について】本プロジェクトには既に無関係の別店舗(千葉県柏市の
「珈琲工房豆壱」mameichi.thebase.in)を対象とした scrape_mameichi.py が
存在するため、名前衝突を避けるためscrape_igamameichi.pyとした。

robots.txt確認済み(2026-09時点): 他のBASE系店舗と同一の記述("Generated by
GRP")。curl/python-requests等は個別にDisallow: /指定があるが、User-agent: *
ルールでは実質許可。本スクレイパーは識別可能な独自User-Agentを使用する。

【商品一覧の取得方法について】
実データ確認済み: sitemap.xml上わずか4件。og:title・
product:price:amountのOGPメタタグから商品名・価格を取得する
(他のBASE系店舗と同じ方式)。この店舗の商品ページには<meta property="og:title">
タグが2個存在する(1個目はサイト全体共通の店舗紹介文、2個目が実際の
「商品名 | 店名 powered by BASE」形式)という他のBASE系店舗には無い
特徴が実データ確認済みのため、末尾(最後)のog:titleタグを採用する処理が
必要。

【非コーヒー豆商品の除外について】
実データ確認済み(全4件):
  - 「おすすめコーヒー「豆」２種（100ｇ×2）送料込」: 商品説明を確認したところ
    「9月のおすすめコーヒー「ウガンダ　エルゴン中深煎り」100gと季節のブレンド
    「秋味ブレンド中深煎り」100gの合計200gです」とあり、月替わりで中身が
    変わる非固定の詰め合わせ(商品名だけでは中身が特定できない)。
    「おまかせ」系の詰め合わせと同種の理由で除外。→「おすすめ」
  - 「ディップスタイルコーヒーバック(伊賀ブレンド＆青山ブレンド）６ 袋」
    「ディップスタイルコーヒーバック　　１０ 袋」: ドリップバッグ形式。
    →「ディップ」
残る「伊賀＆青山ブレンド「豆」２種セット（100g×２）送料込」が対象。
商品説明を確認したところ「深煎「伊賀ブレンド」100gと中煎「青山ブレンド」
100gの合計200gです」と、中身が固定された2種類の自家ブレンド名を明記した
セット商品(「おすすめ」の月替わり品とは異なり中身が常に同じ)であるため、
1商品として対象に含める。

【完全重複リスティングについて】
実データ再確認済み(2026-09-07): sitemap.xmlに上記「伊賀＆青山ブレンド」が
2つの別商品ページ(items/156582019とitems/57673596)として重複掲載されて
いる。両者はog:title・価格(1,860円)・meta descriptionまで完全に同一内容
であり、店舗側の二重出品(旧ページの削除し忘れ)と判断できる。そのため
raw_nameが完全一致する場合は商品URL番号が小さい方(古い方)を正規品として
残し、後から見つかった重複を除外する処理を入れている。
"""

import re

import requests
from bs4 import BeautifulSoup

from coffee_parser import parse_product, detect_stock_status
from previous_data import load_previous_products, is_unchanged

SHOP_INFO = {
    "name": "豆一珈琲",
    "url": "https://www.mameichi.net/",
    "platform": "BASE",
    "address": "三重県伊賀市阿保718-3",
    "prefecture": "三重県",
    "robots_txt_status": "実質許可(2026-09確認。他のBASE系店舗と同一の記述。"
                          "curl/python-requests等は個別にDisallow: /指定あり、"
                          "本スクレイパーは識別可能なUser-Agentを使用)",
}

BASE_URL = "https://www.mameichi.net"
REQUEST_HEADERS = {
    "User-Agent": "CoffeeFinderBot/0.1 (+contact: your-contact-info-here)"
}

NON_BEAN_KEYWORDS = ["おすすめ", "ディップ"]
WEIGHT_PATTERN = re.compile(r"(\d+)\s*[gｇ]")


def fetch_page(url: str) -> BeautifulSoup:
    resp = requests.get(url, headers=REQUEST_HEADERS, timeout=15)
    resp.raise_for_status()
    return BeautifulSoup(resp.text, "html.parser")


def extract_og_fields(soup: BeautifulSoup) -> dict | None:
    # この店舗は<meta property="og:title">が2個存在し、実際の商品名を持つのは
    # 最後の1個(1個目はサイト全体共通の店舗紹介文)。実データ確認済み。
    title_els = soup.select('meta[property="og:title"]')
    if not title_els or not title_els[-1].get("content"):
        return None
    title = title_els[-1]["content"].split(" | ")[0].strip()
    if not title or any(kw in title for kw in NON_BEAN_KEYWORDS):
        return None
    price_el = soup.select_one('meta[property="product:price:amount"]')
    price = int(float(price_el["content"])) if price_el and price_el.get("content") else None
    return {"title": title, "price": price}


def fetch_sitemap_urls() -> list[str]:
    soup = fetch_page(f"{BASE_URL}/sitemap.xml")
    return [loc.get_text(strip=True) for loc in soup.find_all("loc") if "/items/" in loc.get_text()]


def build_record(product_url: str, fields: dict) -> dict | None:
    title = fields["title"]
    parsed = parse_product(title)

    if parsed["is_flavored"]:
        return {
            "shop_name": SHOP_INFO["name"],
            "raw_name": title,
            "category": "フレーバー",
            "is_flavored": True,
            "flavor_name": parsed["flavor_name"],
            "price": fields["price"],
            "product_url": product_url,
        }

    stock_status = detect_stock_status(title)
    weight_m = WEIGHT_PATTERN.search(title)
    weight_g = int(weight_m.group(1)) if weight_m else None

    return {
        "shop_name": SHOP_INFO["name"],
        "raw_name": title,
        "category": parsed["category"],
        "origin_country": parsed["origin_country"],
        "origin_source": parsed["origin_source"],
        "designated_brand": parsed["designated_brand"],
        "processing_method": parsed["processing_method"],
        "grade": parsed["grade"],
        "roast_level": parsed["roast_level"],
        "post_processing_tags": parsed["post_processing_tags"],
        "blend_components": [],
        "price": fields["price"],
        "weight_g": weight_g,
        "stock_status": stock_status,
        "out_of_stock": stock_status != "販売中",
        "product_url": product_url,
    }


def scrape_all_products() -> tuple[list[dict], list[dict]]:
    # sitemap.xml上のURL文字列順ではなく商品ID(末尾の数字)の昇順で処理する。
    # 完全重複リスティング(同一raw_name)が見つかった場合、先に処理された
    # (=IDが小さい、より古い)ものを正規品として残すため。
    product_urls = sorted(fetch_sitemap_urls(), key=lambda u: int(re.search(r"(\d+)$", u).group(1)))
    previous = load_previous_products(SHOP_INFO["name"])

    records = []
    flavored_records = []
    seen_raw_names = set()
    for product_url in product_urls:
        prev = previous.get(product_url)
        try:
            fields = extract_og_fields(fetch_page(product_url))
        except requests.RequestException as e:
            print(f"[warn] 詳細ページ取得失敗: {product_url} ({e})")
            continue
        if not fields:
            continue
        if fields["title"] in seen_raw_names:
            # 完全重複リスティング(店舗側の二重出品)。先に処理済みのURLを正規品
            # として残し、こちらは除外する。
            continue
        seen_raw_names.add(fields["title"])
        if is_unchanged(prev, raw_name=fields["title"]):
            records.append(prev)
            continue

        detail = build_record(product_url, fields)
        if detail is None:
            continue
        if detail.get("is_flavored"):
            flavored_records.append(detail)
        else:
            records.append(detail)

    return records, flavored_records


if __name__ == "__main__":
    import json

    records, flavored_records = scrape_all_products()
    output = {
        "shop": SHOP_INFO,
        "products": records,
        "flavored_products_excluded": flavored_records,
    }
    with open("data_igamameichi.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"[done] {len(records)}件を data_igamameichi.json に出力しました"
          f"(フレーバーコーヒー{len(flavored_records)}件は別枠に分離)")
